// Generated from pinned, visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-african-photo-manifest.mjs after an approved source changes.
export const africanPhotoCandidates = [
  {
    "id": "nigerian-jollof-rice",
    "commonsTitle": "File:A plate of jollof rice and chicken.jpg",
    "title": "A plate of jollof rice and chicken.jpg",
    "author": "Obaniyi covenant",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:A_plate_of_jollof_rice_and_chicken.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/f4/A_plate_of_jollof_rice_and_chicken.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "nigerian-jollof-rice.jpg",
    "sourceAssetSha256": "785a570c36e77db2b6aa8c9834cdb1392ea6830cc4e9cf4e1b944cf9a2fccda4",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A finished serving of Nigerian jollof rice with a chicken accompaniment.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "thieboudienne",
    "commonsTitle": "File:Senegalese Thieboudienne.JPG",
    "title": "Senegalese Thieboudienne.JPG",
    "author": "Mariel.cg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Senegalese_Thieboudienne.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Senegalese_Thieboudienne.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "thieboudienne.jpg",
    "sourceAssetSha256": "ffec155c6cd64113c44353527800fcfcfdcabd2c972cf2ab2395f81daa8e1194",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A Senegalese fish-and-rice platter with vegetables, matching ceebu jën.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "nigerian-egusi-soup",
    "commonsTitle": "File:EGUSI SOUP AND POUNDED YAM.JPG",
    "title": "EGUSI SOUP AND POUNDED YAM.JPG",
    "author": "Ask4ugo",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:EGUSI_SOUP_AND_POUNDED_YAM.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/7f/EGUSI_SOUP_AND_POUNDED_YAM.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "nigerian-egusi-soup.jpg",
    "sourceAssetSha256": "a3dd14bfa7845e468284eb8d0a673269f3c2f3a91a131467a41a201ffdc1d69d",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Nigerian egusi soup with its pounded-yam accompaniment is clearly shown.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "kelewele",
    "commonsTitle": "File:Kelewele, a Ghanaian snack.jpg",
    "title": "Kelewele, a Ghanaian snack.jpg",
    "author": "Maame1Yaa",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Kelewele,_a_Ghanaian_snack.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/ac/Kelewele%2C_a_Ghanaian_snack.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "kelewele.jpg",
    "sourceAssetSha256": "eb66318beda40a6ce190cdfd56cb6a83e0fbf159cc26cc75abaec6904e9d9ba7",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Ghanaian spiced fried plantain chunks are the clearly identifiable finished snack.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "maafe",
    "commonsTitle": "File:Maafé.jpg",
    "title": "Maafé.jpg",
    "author": "Nicolas PHULPIN",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Maaf%C3%A9.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Maaf%C3%A9.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "maafe.jpg",
    "sourceAssetSha256": "a4520031d736e011c7935f25c273a24e98888df42d0eef5a0a4c42bba82fab9d",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A finished Senegalese peanut stew, with vegetables and thick groundnut sauce visible.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "doro-wat",
    "commonsTitle": "File:Ethiopian wat.jpg",
    "title": "Ethiopian wat.jpg",
    "author": "stu_spivack",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ethiopian_wat.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/54/Ethiopian_wat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "doro-wat.jpg",
    "sourceAssetSha256": "ca2b0bb8c66a07fa66ed86a5a3eb3009ef3672460d34a3d4c72262f42e254fb3",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Ethiopian wat with red berbere sauce, traditionally including doro wat variations.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "shiro-wat",
    "commonsTitle": "File:Ethiopian 'Shiro'.JPG",
    "title": "Ethiopian 'Shiro'.JPG",
    "author": "Maheder",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ethiopian_%27Shiro%27.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/43/Ethiopian_%27Shiro%27.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "shiro-wat.jpg",
    "sourceAssetSha256": "1b153fcff5af9a7e3264d5fa3cc6280f57372fae74c629042ee6574190c664c7",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Ethiopian shiro chickpea stew served as a finished dish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "injera",
    "commonsTitle": "File:Injera, Ethiopian bread made from teff a cereal native to Ethiopia.JPG",
    "title": "Injera, Ethiopian bread made from teff a cereal native to Ethiopia.JPG",
    "author": "Visio",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Injera,_Ethiopian_bread_made_from_teff_a_cereal_native_to_Ethiopia.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/37/Injera%2C_Ethiopian_bread_made_from_teff_a_cereal_native_to_Ethiopia.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "injera.jpg",
    "sourceAssetSha256": "3f58c0c9d87c7ea9517ec3dc531b5d436499b8a0565b01279d08c1f8dafe7cb2",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A finished Ethiopian teff injera flatbread with its porous surface.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "nyama-choma",
    "commonsTitle": "File:Nyama choma barbeque.jpg",
    "title": "Nyama choma barbeque.jpg",
    "author": "safaritravelplus",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Nyama_choma_barbeque.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Nyama_choma_barbeque.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "nyama-choma.jpg",
    "sourceAssetSha256": "c1023ad846db4183a67a91c7953db0e63171d56155b60d040e9d09db1735a391",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Kenyan charcoal-grilled nyama choma meat served as the finished dish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "tanzanian-pilau",
    "commonsTitle": "File:African Food - Pilau.JPG",
    "title": "African Food - Pilau.JPG",
    "author": "Richardmwaikambo",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:African_Food_-_Pilau.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/7c/African_Food_-_Pilau.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "tanzanian-pilau.jpg",
    "sourceAssetSha256": "469abc99bf12bd9eaff73e4b9ae9d8e5bad099adf580a72b03c45ccbc0c6e9cc",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A finished plated serving of pilau rice with Swahili-coast spice coloring.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bobotie",
    "commonsTitle": "File:Bobootie 2.JPG",
    "title": "Bobootie 2.JPG",
    "author": "Bli",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bobootie_2.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/6f/Bobootie_2.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "bobotie.jpg",
    "sourceAssetSha256": "6a1ed0c9c16e1118e0d59c3bead806023ed669baed7b13cbea24284fcb90b703",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "South African bobotie with its distinctive browned egg-and-milk topping.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bunny-chow",
    "commonsTitle": "File:Durban's Famous Mutton Bunny Chow.jpg",
    "title": "Durban's Famous Mutton Bunny Chow.jpg",
    "author": "Djreddy1985",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Durban%27s_Famous_Mutton_Bunny_Chow.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/83/Durban%27s_Famous_Mutton_Bunny_Chow.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "bunny-chow.jpg",
    "sourceAssetSha256": "f6ec3da45d96514af7467cd060c173b98b3ef5b42f65ab11c408c0abcabc6bdb",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Durban mutton curry served inside a hollow bread loaf as bunny chow.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "malva-pudding",
    "commonsTitle": "File:Malva pudding with sauce.jpg",
    "title": "Malva pudding with sauce.jpg",
    "author": "Valereee",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Malva_pudding_with_sauce.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Malva_pudding_with_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "malva-pudding.jpg",
    "sourceAssetSha256": "d65023f1ad318b3bce9227be6653bf23876556f21ab58a429e210b1829b5def3",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "South African malva pudding shown with its soaking cream sauce.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  }
];

export default africanPhotoCandidates;
