// Generated from pinned, visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-british-photo-manifest.mjs after an approved source changes.
export const britishPhotoCandidates = [
  {
    "id": "fish-and-chips",
    "commonsTitle": "File:Fish and chips with a pint of cider.jpg",
    "title": "Fish and chips with a pint of cider",
    "author": "Jon Sullivan",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Fish_and_chips_with_a_pint_of_cider.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Fish_and_chips_with_a_pint_of_cider.jpg",
    "license": "Public Domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Licensing",
    "sourceAsset": "fish-and-chips.jpg",
    "sourceAssetSha256": "1cecb617baa24d7587f8b8d0c2f86ee0bf09f32517c47066903cfb5e0d0f9a35",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Traditional battered white fish with thick chips; the cider glass is incidental and does not obscure the dish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "beef-wellington",
    "commonsTitle": "File:Beef Wellington - Crosscut.jpg",
    "title": "Beef Wellington - Crosscut",
    "author": "Parkerman & Christie from San Diego, USA",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Beef_Wellington_-_Crosscut.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/ac/Beef_Wellington_-_Crosscut.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "beef-wellington.jpg",
    "sourceAssetSha256": "26816f523f6687e529576b160b26f8912b7e3c955954a88a751449317b34e852",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Cross-cut Wellington clearly shows rosy beef, mushroom layer and deeply golden puff pastry.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "roast-beef-yorkshire-pudding",
    "commonsTitle": "File:Roastbeef with yorkshire puddings.jpg",
    "title": "Roastbeef with yorkshire puddings",
    "author": "HotBabyHot at German Wikipedia",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Roastbeef_with_yorkshire_puddings.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Roastbeef_with_yorkshire_puddings.jpg",
    "license": "Public Domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Licensing",
    "sourceAsset": "roast-beef-yorkshire-pudding.jpg",
    "sourceAssetSha256": "818c8b58fbc2438caceb30d6b07f1a61b1232a9b2d123ba35d682ad9ed7396b6",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Traditional roast beef plate with visible Yorkshire puddings and brown gravy.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "shepherds-pie",
    "commonsTitle": "File:Shepherds pie (6962180559).jpg",
    "title": "Shepherds pie (6962180559)",
    "author": "cyclonebill from Copenhagen, Denmark",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Shepherds_pie_(6962180559).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/75/Shepherds_pie_%286962180559%29.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "shepherds-pie.jpg",
    "sourceAssetSha256": "8107f4f2b8b06c129d8bbbef1863a375ba35782a2fee4cc6c9840f1a4b1df1cf",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Served shepherd's pie clearly shows the browned mashed-potato layer and moist minced-meat-and-vegetable filling.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "toad-in-the-hole",
    "commonsTitle": "File:Toad in the hole.jpg",
    "title": "Toad in the hole",
    "author": "Robert Gibert",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Toad_in_the_hole.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/01/Toad_in_the_hole.jpg",
    "license": "Public Domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Licensing",
    "sourceAsset": "toad-in-the-hole.jpg",
    "sourceAssetSha256": "5325842dd2282dca05b52b5f319be7d72553621820aa8e2a9138e58c15f75cd4",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Browned sausages are visibly embedded in a dramatically risen, crisp Yorkshire-pudding batter.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "cornish-pasty",
    "commonsTitle": "File:Cornish pasty.jpeg",
    "title": "Cornish pasty",
    "author": "David Johnson [1]",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Cornish_pasty.jpeg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Cornish_pasty.jpeg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceAsset": "cornish-pasty.jpg",
    "sourceAssetSha256": "78fcb2310cbeeada47208bf6c3905e56c1d77608c49899217c8766f364ef24d5",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Deep-golden traditional Cornish pasty with a sturdy D-shaped shell and prominent crimp.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "full-english-breakfast",
    "commonsTitle": "File:Full English Bigger Breakfast, Sainsbury's Low Hall, Chingford, London, England focus 1.jpg",
    "title": "Full English Bigger Breakfast, Sainsbury's Low Hall, Chingford, London, England focus 1",
    "author": "Acabashi",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Full_English_Bigger_Breakfast,_Sainsbury%27s_Low_Hall,_Chingford,_London,_England_focus_1.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Full_English_Bigger_Breakfast%2C_Sainsbury%27s_Low_Hall%2C_Chingford%2C_London%2C_England_focus_1.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "full-english-breakfast.jpg",
    "sourceAssetSha256": "a78b3099a38d1fc415f4acac95917ff5a790f762bea805ad5aee289a5f7d662e",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Generous full English plate with fried eggs, black pudding, sausages, bacon, beans, tomato and toast clearly separated.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "chicken-tikka-masala",
    "commonsTitle": "File:Chicken Tikka Masala-01.jpg",
    "title": "Chicken Tikka Masala-01",
    "author": "hellosputnik",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Chicken_Tikka_Masala-01.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Chicken_Tikka_Masala-01.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "chicken-tikka-masala.jpg",
    "sourceAssetSha256": "9d4e3dec38c447849dc6548047fd3aa861f3137f1162465cd3ad7023f3126afb",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Clear orange-red chicken tikka masala with visible chicken pieces, glossy curry-house sauce and restrained herb garnish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "cullen-skink",
    "commonsTitle": "File:Cullen Skink.JPG",
    "title": "Cullen Skink",
    "author": "Metukkalihis",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Cullen_Skink.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Cullen_Skink.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "cullen-skink.jpg",
    "sourceAssetSha256": "9813c34809d209fb9c76dbf5320251f3f3d7b25b3d9b589eaffcfa569c22f466",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Pale creamy Cullen skink with visible smoked-fish flakes and potato pieces.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "welsh-rarebit",
    "commonsTitle": "File:Welsh rarebit.JPG",
    "title": "Welsh rarebit",
    "author": "Worm That Turned",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Welsh_rarebit.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Welsh_rarebit.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "welsh-rarebit.jpg",
    "sourceAssetSha256": "93419e6f3affff4608712d1582f024313da27ffce4da52b4cd59aa7fcd71ec3b",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Toast covered by a thick smooth grilled cheese mixture with deep browned blistering and crisp bread edges.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "sticky-toffee-pudding",
    "commonsTitle": "File:Sticky toffee pudding at the Black Swan - Stierch.jpg",
    "title": "Sticky toffee pudding at the Black Swan - Stierch",
    "author": "Sarah Stierch",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Sticky_toffee_pudding_at_the_Black_Swan_-_Stierch.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Sticky_toffee_pudding_at_the_Black_Swan_-_Stierch.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "sticky-toffee-pudding.jpg",
    "sourceAssetSha256": "ef59659bb58cda0c9bfe6628eee18c4b70f20e8bd63e8a0f84f06bc7611c7c6a",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Dark date sponge served warm with abundant glossy toffee sauce.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "traditional-trifle",
    "commonsTitle": "File:Trifle.jpg",
    "title": "Trifle",
    "author": "-- Ben 18:33, 25 March 2006 (UTC)",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Trifle.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/01/Trifle.jpg",
    "license": "Public Domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Licensing",
    "sourceAsset": "traditional-trifle.jpg",
    "sourceAssetSha256": "22c89faf8c44f406b2869b588835b1e14ed3156c6dced1f687cd5f4234a0975a",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Clear glass trifle bowl shows distinct red jelly-and-fruit, pale custard and generous white cream layers.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "steak-and-kidney-pie",
    "commonsTitle": "File:Steak & Kidney Pie - 3 3 2019 (46565695054).jpg",
    "title": "Steak & Kidney Pie - 3 3 2019 (46565695054)",
    "author": "CharmaineZoe's Marvelous Melange from England",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Steak_%26_Kidney_Pie_-_3_3_2019_(46565695054).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Steak_%26_Kidney_Pie_-_3_3_2019_%2846565695054%29.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "steak-and-kidney-pie.jpg",
    "sourceAssetSha256": "5721ed2d94e0061e47501b85f37c3979a6645880497941d80c94447b29ab0507",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Traditional steak-and-kidney pie in a ceramic dish with a very high, crisp, deeply golden puff-pastry lid.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  }
];

export default britishPhotoCandidates;
