// Generated from pinned, visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-canadian-photo-manifest.mjs after an approved source changes.
export const canadianPhotoCandidates = [
  {
    "id": "poutine",
    "commonsTitle": "File:Poutine! (422692736).jpg",
    "title": "Poutine! (422692736).jpg",
    "author": "Joe Shlabotnik from Forest Hills, Queens, USA",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Poutine!_(422692736).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Poutine%21_%28422692736%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "poutine.jpg",
    "sourceAssetSha256": "e6e1bd88bae1826ce468ade23b587ffbb8bc0e9daf3d2a33100b4f54d0a88c91",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "Classic golden fries, cheese curds and brown gravy are visible together in the finished Québec dish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "tourtiere",
    "commonsTitle": "File:Tourtiere half.jpg",
    "title": "Tourtiere half.jpg",
    "author": "Al Mendelsohn",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Tourtiere_half.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Tourtiere_half.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "tourtiere.jpg",
    "sourceAssetSha256": "0d3be465b3f6e5c144b7f55bf0548c88987b12a85b6983baf98426465e19378c",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "A Québec tourtière is shown cut open with its meat filling and flaky crust visible.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "montreal-smoked-meat-sandwich",
    "commonsTitle": "File:Montreal Style Smoked Meat Sandwich.jpg",
    "title": "Montreal Style Smoked Meat Sandwich.jpg",
    "author": "Mixwell",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Montreal_Style_Smoked_Meat_Sandwich.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/62/Montreal_Style_Smoked_Meat_Sandwich.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "montreal-smoked-meat-sandwich.jpg",
    "sourceAssetSha256": "db22bc1b2f2d70489a7fdaf973c0d4c277eef86974a9b3c598116942964914f5",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "Finished Montréal smoked-meat sandwich and accompaniments are the clear subject.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "montreal-style-bagels",
    "commonsTitle": "File:Montreal Bagel by Fairmount Bagels.jpg",
    "title": "Montreal Bagel by Fairmount Bagels.jpg",
    "author": "Gogerr",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Montreal_Bagel_by_Fairmount_Bagels.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/29/Montreal_Bagel_by_Fairmount_Bagels.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "montreal-style-bagels.jpg",
    "sourceAssetSha256": "289cc8c71d154e25e286345856f420ff81ede1f3f477098359b81b9bb0cf1850",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "A sesame Montreal-style bagel from Fairmount is shown close enough to recognize its distinctive ring and crust.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "butter-tarts",
    "commonsTitle": "File:ButtertartS1360020.jpg",
    "title": "ButtertartS1360020.jpg",
    "author": "Alex Lozupone",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:ButtertartS1360020.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/30/ButtertartS1360020.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "butter-tarts.jpg",
    "sourceAssetSha256": "ccff425f48c0e1088f7ef84dffda4269136d63ad84c5113f0bdab19c8d1a529f",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "Canadian butter tarts with glossy filling and pastry shells are clearly visible.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "nanaimo-bars",
    "commonsTitle": "File:Nanaimo Bars, stacked.jpg",
    "title": "Nanaimo Bars, stacked.jpg",
    "author": "Craig Dugas",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Nanaimo_Bars,_stacked.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/49/Nanaimo_Bars%2C_stacked.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "nanaimo-bars.jpg",
    "sourceAssetSha256": "fbad6a2a529facc7c886100c3976f50c37ac49b36fa78cf7d602814ba6113dd3",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "Stacked Nanaimo bars show the crumb base, custard layer and chocolate top.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "peameal-bacon-sandwich",
    "commonsTitle": "File:Peameal bacon sandwich.jpg",
    "title": "Peameal bacon sandwich.jpg",
    "author": "Leventio",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Peameal_bacon_sandwich.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Peameal_bacon_sandwich.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "peameal-bacon-sandwich.jpg",
    "sourceAssetSha256": "05487a6aa4898f0d352cc85244b87d1ccf9cde93f45177e8ad8c32d1e38f0ad2",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "Ontario peameal bacon is served in a bun as the subject of the photograph.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "halifax-donair",
    "commonsTitle": "File:Donair (4307999410).jpg",
    "title": "Donair (4307999410).jpg",
    "author": "Morgan from Montreal, Quebec, Canada",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Donair_(4307999410).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Donair_%284307999410%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "halifax-donair.jpg",
    "sourceAssetSha256": "db3c4513ff0079ae28bfa63eecce63d276a088683c8a2a46284d2285e03003b8",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "A Halifax donair with its signature sweet garlic sauce is shown as a prepared street-food dish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "jiggs-dinner",
    "commonsTitle": "File:Jiggs Dinner.jpg",
    "title": "Jiggs Dinner.jpg",
    "author": "Alycmy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Jiggs_Dinner.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/46/Jiggs_Dinner.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "jiggs-dinner.jpg",
    "sourceAssetSha256": "17e6e9e2f67505dce6dffa77ff6e30feb7030dd3374039177445b2dbe1941a6a",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "A Newfoundland boiled dinner is plated with salt meat and its characteristic root vegetables.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "toutons",
    "commonsTitle": "File:Touton - Canadian breakfast food.jpg",
    "title": "Touton - Canadian breakfast food.jpg",
    "author": "Bigmacthealmanac",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Touton_-_Canadian_breakfast_food.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/f5/Touton_-_Canadian_breakfast_food.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "toutons.jpg",
    "sourceAssetSha256": "4d6141db3e8f7b0c8409d7335584540ecc39087d276703134290f439d9a80001",
    "cropPosition": "east",
    "cropZoom": 1.35,
    "reviewedAt": "2026-09-19",
    "reviewNote": "A single golden Newfoundland touton is prominent; the crop favours the food and trims unrelated breakfast packaging.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "saskatoon-berry-pie",
    "commonsTitle": "File:2020 366 130 A Saskatoon Berry Pie (49915105891).jpg",
    "title": "2020 366 130 A Saskatoon Berry Pie (49915105891).jpg",
    "author": "Alan Levine from Archydal, Canada",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:2020_366_130_A_Saskatoon_Berry_Pie_(49915105891).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/a4/2020_366_130_A_Saskatoon_Berry_Pie_%2849915105891%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "saskatoon-berry-pie.jpg",
    "sourceAssetSha256": "bcbf74ed5f663b6560120d7314cd036a24186820c88715e1fad704a8094b6140",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "The Saskatoon berry pie is clearly identifiable in its baked crust and purple berry filling.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "maple-taffy",
    "commonsTitle": "File:Maple syrup popsicle (6974621697).jpg",
    "title": "Maple syrup popsicle (6974621697).jpg",
    "author": "Jaime Walker from Ottawa, Canada",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Maple_syrup_popsicle_(6974621697).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/b8/Maple_syrup_popsicle_%286974621697%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "maple-taffy.jpg",
    "sourceAssetSha256": "69fc02c83852e58141a582516023b1abbaa15db39b7754cda24842316cbf947d",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "A maple taffy ribbon is being rolled onto a stick over snow, visibly matching the recipe.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "campfire-bannock",
    "commonsTitle": "File:Bannock 2.JPG",
    "title": "Bannock 2.JPG",
    "author": "Carl Steinbeißer",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bannock_2.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Bannock_2.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "campfire-bannock.jpg",
    "sourceAssetSha256": "5d0311c8bea800fa7e996c426a0b97c1ee69282b47e3ee5f81b1f1b4c6dd24c9",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-19",
    "reviewNote": "Bannock cooks over a campfire in a pot, matching the documented campfire adaptation.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  }
];

export default canadianPhotoCandidates;
