// Generated from pinned, visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-french-photo-manifest.mjs after an approved source changes.
export const frenchPhotoCandidates = [
  {
    "id": "french-onion-soup",
    "commonsTitle": "File:Onion soup, Balthazar.jpg",
    "title": "Onion soup, Balthazar",
    "author": "Ralph Daily",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Onion_soup,_Balthazar.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/90/Onion_soup%2C_Balthazar.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "french-onion-soup.jpg",
    "sourceAssetSha256": "0718f8fed8053b11efb699b21f5d1d7205cf04bd667fc1071362fe624a4e4d8a",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "White ovenproof crock under a continuous browned cheese cap with parsley; the toast is covered by the cheese as expected.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "ratatouille",
    "commonsTitle": "File:Ratatouille.jpg",
    "title": "Ratatouille",
    "author": "Marcus Guimarães",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ratatouille.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/27/Ratatouille.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "ratatouille.jpg",
    "sourceAssetSha256": "f5022ecaa9d9b402946dc9ac6d904404a12af6a776f831bc79f6b44bf153b104",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Distinct cooked eggplant, zucchini, red/yellow pepper and tomato pieces with herbs and olive-oil sheen; no layered gratin or cheese.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "gratin-dauphinois",
    "commonsTitle": "File:Gratin dauphinois.jpg",
    "title": "Gratin dauphinois",
    "author": "Ludovic Péron",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gratin_dauphinois.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Gratin_dauphinois.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "gratin-dauphinois.jpg",
    "sourceAssetSha256": "79ca9bd37caf98b3161c697050d57a9adf83eedf0d3712c077e2eae9fe6ce685",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Creamy baked potato slices in a white oval dish with a browned dairy crust and parsley; no meat garnish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "boeuf-bourguignon",
    "commonsTitle": "File:Beef bourguignon-01.jpg",
    "title": "Beef bourguignon-01",
    "author": "balise42",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Beef_bourguignon-01.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/80/Beef_bourguignon-01.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "boeuf-bourguignon.jpg",
    "sourceAssetSha256": "9b80399be544db9de0cc526802a9b490258e669fb9ddf117e1342753e11be258",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Large beef pieces with mushrooms, carrot and onions in brown-red sauce, with plain boiled potatoes and parsley alongside.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "coq-au-vin",
    "commonsTitle": "File:Coq au vin-03.jpg",
    "title": "Coq au vin-03",
    "author": "Ewan-M",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Coq_au_vin-03.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/fe/Coq_au_vin-03.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "coq-au-vin.jpg",
    "sourceAssetSha256": "667f48df97c8b19d729249ace484cddbcfa275a1c548e1a1e714d4632f80e466",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Dark wine-braised chicken with bacon, mushrooms and parsley over pale mashed potato; no cream sauce, sausage or rice.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "blanquette-de-veau",
    "commonsTitle": "File:Blanquette de veau 1.jpg",
    "title": "Blanquette de veau 1",
    "author": "Sebring12Hrs",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Blanquette_de_veau_1.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Blanquette_de_veau_1.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "blanquette-de-veau.jpg",
    "sourceAssetSha256": "f8be95e257d248b1c5d36d04672aef96e7b278f7e7379229647d654a2c7ca6ea",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Veal with carrot and mushrooms in a smooth pale sauce over rice with black pepper; selected instead of the grainier candidate.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "poulet-basquaise",
    "commonsTitle": "File:Poulet basquaise 01.jpg",
    "title": "Poulet basquaise 01",
    "author": "Arnaud 25",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Poulet_basquaise_01.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/98/Poulet_basquaise_01.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "poulet-basquaise.jpg",
    "sourceAssetSha256": "287621aaa34d81dc3736419047c75e27acffe5089a3ca1bb466e5c821952ad93",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Chicken portions in red tomato sauce with chunky red/green peppers and softened onion; no cream or sausage.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "quiche-lorraine",
    "commonsTitle": "File:Quiche de Lorraine.jpg",
    "title": "Quiche de Lorraine",
    "author": "Donna Alvita",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Quiche_de_Lorraine.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/43/Quiche_de_Lorraine.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "quiche-lorraine.jpg",
    "sourceAssetSha256": "164db90cd0c6b9ec525a9e4d654b6c964a4c89107733dd3781a8b70d0f7ff90f",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Round quiche with golden crust, pale set custard and short bacon strips; no vegetables or lattice topping.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "croque-monsieur",
    "commonsTitle": "File:Croque monsieur.jpg",
    "title": "Croque monsieur",
    "author": "Michael Brewer",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Croque_monsieur.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Croque_monsieur.jpg",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceAsset": "croque-monsieur.jpg",
    "sourceAssetSha256": "09597274a04ed347d07a5a03fd431aacdbb3f483b38be6bbdf46f8cd19e36e9c",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Two toasted white-bread slices with folded ham and cheese under a melted cheese/béchamel top; no egg, lettuce or tomato.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "sole-meuniere",
    "commonsTitle": "File:Sole meuniere (4689490702).jpg",
    "title": "Sole meuniere (4689490702)",
    "author": "Jay Cross from Berkeley, California, US",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Sole_meuniere_(4689490702).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Sole_meuniere_%284689490702%29.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "sole-meuniere.jpg",
    "sourceAssetSha256": "aed1ba69e319171ec25d0b6be46adafcfabbaf3bad1a0abaac908819dbb5e894",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Whole flatfish with tail intact, lightly browned crust, lemon, parsley and green beans; no rolled fillets or shrimp.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "moules-marinieres",
    "commonsTitle": "File:Moules marinières.jpg",
    "title": "Moules marinières",
    "author": "Thomon",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Moules_marini%C3%A8res.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/68/Moules_marini%C3%A8res.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "moules-marinieres.jpg",
    "sourceAssetSha256": "ede9227cd326110347ae64d8ce81397e8a845b83c4b54e087a86159b13fe3458",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Open black mussels with orange flesh in pale white-wine cooking juices and green herb flecks; no cream, fries or prominent tomato.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "salade-nicoise",
    "commonsTitle": "File:Salade niçoise 001.jpg",
    "title": "Salade niçoise 001",
    "author": "Arnaud 25",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Salade_ni%C3%A7oise_001.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/c/ca/Salade_ni%C3%A7oise_001.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "salade-nicoise.jpg",
    "sourceAssetSha256": "e1e31c682b9b1b1f764b0865b787fb224b835fb0c7d258441ced77582d99209e",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Tuna, anchovy, hard-boiled egg, artichoke, black olives, onion rings and vegetables over lettuce; no rare tuna steak.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "salade-lyonnaise",
    "commonsTitle": "File:Salade lyonnaise.JPG",
    "title": "Salade lyonnaise",
    "author": "Arnaud 25",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Salade_lyonnaise.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/ed/Salade_lyonnaise.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "salade-lyonnaise.jpg",
    "sourceAssetSha256": "5e4d4ac510661a1ff01e03d8416cbcbd14d398b9283b672b4c222a9ee546fa48",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Mixed lettuce with crisp bacon, croutons and an intact poached egg; no chicken liver or cheese.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "french-crepes",
    "commonsTitle": "File:Crepes dsc07085.jpg",
    "title": "Crepes dsc07085",
    "author": "David Monniaux",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Crepes_dsc07085.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/09/Crepes_dsc07085.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceAsset": "french-crepes.jpg",
    "sourceAssetSha256": "bfcaa02f1bd976f0a5b85c9a9aaa2a95bb957b47c65080085f624ba2214bd3ab",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Plain stack of thin golden wheat crêpes without cream, fruit, chocolate or savoury filling.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "creme-brulee",
    "commonsTitle": "File:Crème brûlée at restaurant in Zushi.jpg",
    "title": "Crème brûlée at restaurant in Zushi",
    "author": "Syced",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Cr%C3%A8me_br%C3%BBl%C3%A9e_at_restaurant_in_Zushi.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Cr%C3%A8me_br%C3%BBl%C3%A9e_at_restaurant_in_Zushi.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "creme-brulee.jpg",
    "sourceAssetSha256": "4772dec59ab33ed480a46c647aec9e1ac1d5974050e1dffff28764bc2850bf52",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Single white ramekin with pale custard beneath a thin amber brûléed crust and a small spoon; no berry or cream garnish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "tarte-tatin",
    "commonsTitle": "File:Franse tarte tatin.jpg",
    "title": "Franse tarte tatin",
    "author": "Djenghisz",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Franse_tarte_tatin.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/1/16/Franse_tarte_tatin.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "tarte-tatin.jpg",
    "sourceAssetSha256": "fd865fa7edf4eb6f8a2774ec90fbd68a29137e4750dd5b12035f98bd72c632e9",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Round upside-down tart with tightly packed glossy amber apple halves; no lattice, raw slices or whipped cream.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "madeleines",
    "commonsTitle": "File:Madeleine 01.JPG",
    "title": "Madeleine 01",
    "author": "Un Chausson",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Madeleine_01.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Madeleine_01.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "madeleines.jpg",
    "sourceAssetSha256": "102c36624a4c7c6a0d59f22d4b313a6c1dc5f98fabe25c9c4f66980a32bb349f",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Plain golden shell-shaped madeleines with crisp ridges and rounded humps; no glaze, chocolate or powdered sugar.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "clafoutis",
    "commonsTitle": "File:Clafoutis cerises.jpg",
    "title": "Clafoutis cerises",
    "author": "Popo le Chien",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Clafoutis_cerises.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Clafoutis_cerises.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "clafoutis.jpg",
    "sourceAssetSha256": "7650509c5e399bd424c4a2974bf6e0214750b954dc799b665bc32e661513de06",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Cherry clafoutis with dark cherries embedded in a lightly browned custard and a clean wedge cut; no pastry crust or frosting.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "chocolate-mousse",
    "commonsTitle": "File:Chocolate coffee mousse.jpg",
    "title": "Chocolate coffee mousse",
    "author": "Lu from Seattle, USA",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Chocolate_coffee_mousse.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Chocolate_coffee_mousse.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "chocolate-mousse.jpg",
    "sourceAssetSha256": "f46b7c2ee4591fc2dda04d50735820c955b136c4776aa28ef242f87df40e9607",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Pure dark airy chocolate mousse with a matte surface and spooned texture; serving vessel is a white bowl rather than the preferred clear glasses.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "gougeres",
    "commonsTitle": "File:Des gougères en apéritif - restaurant Place Bernard (février 2023).jpg",
    "title": "Des gougères en apéritif - restaurant Place Bernard (février 2023)",
    "author": "Benoît Prieur",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Des_goug%C3%A8res_en_ap%C3%A9ritif_-_restaurant_Place_Bernard_(f%C3%A9vrier_2023).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Des_goug%C3%A8res_en_ap%C3%A9ritif_-_restaurant_Place_Bernard_%28f%C3%A9vrier_2023%29.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "gougeres.jpg",
    "sourceAssetSha256": "61fed63343fe8f94374d451627ba4466c87ce19036c9bd39d9178a45ef0693a8",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Plain deeply golden cheese puffs with irregular crisp tops; one puff is split enough to show the light hollow interior, with no filling or glaze.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "financiers",
    "commonsTitle": "File:Financiers - Patisserie - 002.jpg",
    "title": "Financiers - Patisserie - 002",
    "author": "Thesupermat",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Financiers_-_Patisserie_-_002.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/52/Financiers_-_Patisserie_-_002.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "financiers.jpg",
    "sourceAssetSha256": "b55062a23b62a282ff805334f1166597a2c178a7169010aa83592d36e783abc9",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Plain rectangular financiers with golden tops, darker crisp edges and a cut piece exposing moist fine crumb; fewer pieces than the ideal eight-piece composition.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  }
];

export default frenchPhotoCandidates;
