// Generated from pinned, visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-greek-photo-manifest.mjs after an approved source changes.
export const greekPhotoCandidates = [
  {
    "id": "moussaka",
    "commonsTitle": "File:Greece Food Moussaka.JPG",
    "title": "Greece Food Moussaka",
    "author": "User:Jpatokal",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Greece_Food_Moussaka.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/20/Greece_Food_Moussaka.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "moussaka.jpg",
    "sourceAssetSha256": "cbd6bb265db74c19b2269de5d2522961743f3b33383d8a46321cc1c63d2000f3",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Traditional moussaka with a browned béchamel cap and clearly layered eggplant/meat interior.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pastitsio",
    "commonsTitle": "File:Greek pastitsio.jpg",
    "title": "Greek pastitsio",
    "author": "Katrin Morenz from Aachen, Deutschland",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Greek_pastitsio.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Greek_pastitsio.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "pastitsio.jpg",
    "sourceAssetSha256": "820c97c8ad99089b0813396e7e550af6dc3b7f508a43f48c0b8c7501401c4ed9",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Greek pastitsio showing baked tubular pasta, meat sauce and a thick pale-golden béchamel layer.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pork-souvlaki",
    "commonsTitle": "File:Souvlaki and potato fries.jpg",
    "title": "Souvlaki and potato fries",
    "author": "Andrew Davidoff",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Souvlaki_and_potato_fries.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Souvlaki_and_potato_fries.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "pork-souvlaki.jpg",
    "sourceAssetSha256": "37fa0dbe29ce556d8b59a90925b891e3cd7f56129bdae1a6e2a977887af3b864",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Finished souvlaki skewers with evenly cut browned meat cubes and crisp edges, closely matching the grilled pork-skewer presentation.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "spanakopita",
    "commonsTitle": "File:Spanikopita Greek dish.jpg",
    "title": "Spanikopita Greek dish",
    "author": "Tanya Bakogiannis",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Spanikopita_Greek_dish.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/23/Spanikopita_Greek_dish.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceAsset": "spanakopita.jpg",
    "sourceAssetSha256": "e984dea928e22236b6a87e52c5e14b63dc9785cc48fb240b96a461e8e4b19b2f",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Golden spanakopita with visibly flaky phyllo and a dense spinach filling.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "dolmades",
    "commonsTitle": "File:Dolmadakia.JPG",
    "title": "Dolmadakia",
    "author": "Saintfevrier",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Dolmadakia.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/fb/Dolmadakia.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "dolmades.jpg",
    "sourceAssetSha256": "2f6ddf4f9d3e24c607fca0ebd00eef64d8b3a2d2c3fb95bc5c91741de5ab082d",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Small intact Greek dolmadakia rolls with glossy vine leaves in a simple serving.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "avgolemono",
    "commonsTitle": "File:Avgolemono - Sarah Stierch.jpg",
    "title": "Avgolemono - Sarah Stierch",
    "author": "Missvain",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Avgolemono_-_Sarah_Stierch.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Avgolemono_-_Sarah_Stierch.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceAsset": "avgolemono.jpg",
    "sourceAssetSha256": "4674d98f36ba21ac01e8e40568649111d034067a3f018a4a324f66ef595d698b",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Pale creamy avgolemono soup with the defining silky egg-lemon appearance.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "fasolada",
    "commonsTitle": "File:Fasolada.JPG",
    "title": "Fasolada",
    "author": "Miansari66",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Fasolada.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/91/Fasolada.JPG",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "fasolada.jpg",
    "sourceAssetSha256": "d0aa906cbe9a0cf90579c7774bc552db290da2ff25737d625bcc01d93ec04c41",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Rustic Greek fasolada with visible white beans in a tomato-rich broth.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "gigantes-plaki",
    "commonsTitle": "File:Gigandes plaki.jpg",
    "title": "Gigandes plaki",
    "author": "Hevesli",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gigandes_plaki.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/be/Gigandes_plaki.jpg",
    "license": "Public Domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Licensing",
    "sourceAsset": "gigantes-plaki.jpg",
    "sourceAssetSha256": "71a0b95a9af9c2adb170d02d0fe5f31a367b880a39636662287c42c324829ef5",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Baked giant white beans in a thick red tomato sauce, matching gigantes plaki closely.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "gemista",
    "commonsTitle": "File:Gemista.jpg",
    "title": "Gemista",
    "author": "Photo and cooking: Badseed",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gemista.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Gemista.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceAsset": "gemista.jpg",
    "sourceAssetSha256": "da06b26cc1f5e453a5801e1ef90b27e32a0b7951208dcb3155ada79a13e2430e",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Traditional gemista with whole stuffed tomatoes and peppers visibly softened from roasting.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "beef-stifado",
    "commonsTitle": "File:20240503 Stifado Restaurant MeGusto anagoria.jpg",
    "title": "20240503 Stifado Restaurant MeGusto anagoria",
    "author": "Anagoria",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:20240503_Stifado_Restaurant_MeGusto_anagoria.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/d/d8/20240503_Stifado_Restaurant_MeGusto_anagoria.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "beef-stifado.jpg",
    "sourceAssetSha256": "da3646eda5ffe399d8066646f52918c3f866eabdaf15345ee654f046e43e974e",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Excellent stifado close view with large tender beef pieces, many intact small onions and a thick glossy red-brown sauce.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "keftedes",
    "commonsTitle": "File:Fried homemade meatballs.jpg",
    "title": "Fried homemade meatballs",
    "author": "Biser Todorov",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Fried_homemade_meatballs.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/b8/Fried_homemade_meatballs.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceAsset": "keftedes.jpg",
    "sourceAssetSha256": "ec2fd3c14fcfbfd9fa45523aa0143bd80ef99c82fbb6426756ea440556a43a77",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Deep-browned fried meatballs with a home-style texture; visually close to Greek keftedes despite generic source naming.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "horiatiki",
    "commonsTitle": "File:Greece Food Horiatiki.JPG",
    "title": "Greece Food Horiatiki",
    "author": "User:Jpatokal",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Greece_Food_Horiatiki.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Greece_Food_Horiatiki.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "horiatiki.jpg",
    "sourceAssetSha256": "d475f81b950bcf8069b97fc3e6f71282b7e63918efe1306ef26fe99afd8c8b17",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Authentic-looking Greek village salad with large tomato and cucumber pieces, olives and a substantial feta slab.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "galaktoboureko",
    "commonsTitle": "File:Galaktoboureko.jpg",
    "title": "Galaktoboureko",
    "author": "Badseed",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Galaktoboureko.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Galaktoboureko.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceAsset": "galaktoboureko.jpg",
    "sourceAssetSha256": "0b672771690a3f791e16ba4f1721872252dabdab8e2d1da4d1d7f9d28664975a",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-14",
    "reviewNote": "Galaktoboureko slice with crisp phyllo around a thick pale custard centre and syrup sheen.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  }
];

export default greekPhotoCandidates;
