// Generated from visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-indian-photo-manifest.mjs after an approved source changes.
export const indianPhotoCandidates = [
  {
    "id": "butter-chicken",
    "commonsTitle": "File:Chicken makhani.jpg",
    "title": "Chicken makhani",
    "author": "stu_spivack",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Chicken_makhani.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Chicken_makhani.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "butter-chicken.jpg",
    "sourceAssetSha256": "b046e679d941ca9e3c2c770ed4d55949c94d319b3b2fa683001e37d8b35ae667",
    "cropPosition": "attention"
  },
  {
    "id": "palak-paneer",
    "commonsTitle": "File:Palak Paneer (Cottage cheese in spinach gravy).jpg",
    "title": "Palak Paneer (Cottage cheese in spinach gravy)",
    "author": "DreamyFlutura11",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Palak_Paneer_(Cottage_cheese_in_spinach_gravy).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Palak_Paneer_%28Cottage_cheese_in_spinach_gravy%29.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "palak-paneer.jpg",
    "sourceAssetSha256": "5fd32ed085b2617eced45b15f778f293cece1e5941e9a2eb7d91c10cba0629da",
    "cropPosition": "attention"
  },
  {
    "id": "chana-masala",
    "commonsTitle": "File:Chana masala (5727362126).jpg",
    "title": "Chana masala (5727362126)",
    "author": "Johan Bichel Lindegaard from Copenhagen, Denmark",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Chana_masala_(5727362126).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/93/Chana_masala_%285727362126%29.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "chana-masala.jpg",
    "sourceAssetSha256": "a60285119b69286fcc73965e235fd568093c88283986020efac510546271fcc6",
    "cropPosition": "attention"
  },
  {
    "id": "dal-tadka",
    "commonsTitle": "File:Dal Tadka.jpg",
    "title": "Dal Tadka",
    "author": "Monali.mishra",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Dal_Tadka.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Dal_Tadka.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "dal-tadka.jpg",
    "sourceAssetSha256": "3c5be6119e6918e2ddabe39c799a258f98f4d1b34ec58c7220f1273c75b5bf63",
    "cropPosition": "attention"
  },
  {
    "id": "rajma-masala",
    "commonsTitle": "File:Rajma, kidney beans, served with chawal, rice.jpg",
    "title": "Rajma, kidney beans, served with chawal, rice",
    "author": "rovingI",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Rajma,_kidney_beans,_served_with_chawal,_rice.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Rajma%2C_kidney_beans%2C_served_with_chawal%2C_rice.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "rajma-masala.jpg",
    "sourceAssetSha256": "605273da19bceb3ec2310893d821d6f145458e8b9c0980c66e21604ddd27dd05",
    "cropPosition": "attention"
  },
  {
    "id": "aloo-gobi",
    "commonsTitle": "File:Gobi-aloo ki sabji by me, location - my kitchen, meerut, state - Uttar Pradesh, 0002.jpg",
    "title": "Gobi-aloo ki sabji by me, location - my kitchen, meerut, state - Uttar Pradesh, 0002",
    "author": "Ifrasaifi12",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gobi-aloo_ki_sabji_by_me,_location_-_my_kitchen,_meerut,_state_-_Uttar_Pradesh,_0002.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Gobi-aloo_ki_sabji_by_me%2C_location_-_my_kitchen%2C_meerut%2C_state_-_Uttar_Pradesh%2C_0002.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "aloo-gobi.jpg",
    "sourceAssetSha256": "4e543a03f4a0680901934f5bc52d694eec9ab17532a2d5391d018e92f1f2015f",
    "cropPosition": "attention"
  },
  {
    "id": "baingan-bharta",
    "commonsTitle": "File:Baigan ka Bharta.jpg",
    "title": "Baigan ka Bharta",
    "author": "Devika",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Baigan_ka_Bharta.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/33/Baigan_ka_Bharta.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "baingan-bharta.jpg",
    "sourceAssetSha256": "0dc3cb81c0e1b51b173de22d323bf63c7cd2310f6aa450d84287a3c407615625",
    "cropPosition": "attention"
  },
  {
    "id": "hyderabadi-chicken-biryani",
    "commonsTitle": "File:Hyderabadi Chicken Biryani.jpg",
    "title": "Hyderabadi Chicken Biryani",
    "author": "Garrett Ziegler from New York, United States",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Hyderabadi_Chicken_Biryani.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Hyderabadi_Chicken_Biryani.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "hyderabadi-chicken-biryani.jpg",
    "sourceAssetSha256": "74424e181f562a48238c4c582d2dc320de870675f9151356dc3b3f55adf0b530",
    "cropPosition": "attention"
  },
  {
    "id": "masala-dosa",
    "commonsTitle": "File:Masala dosa.jpg",
    "title": "Masala dosa",
    "author": "https://www.flickr.com/photos/mckaysavage/",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Masala_dosa.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/58/Masala_dosa.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "masala-dosa.jpg",
    "sourceAssetSha256": "df22d306c8fd0fac163c0c1039c98c7ab9192e69c1ff8f0b5f478c87b624afe0",
    "cropPosition": "attention"
  },
  {
    "id": "idli-sambar",
    "commonsTitle": "File:Idli, sambar and coconut chutney.jpg",
    "title": "Idli, sambar and coconut chutney",
    "author": "arvind grover from New York City, USA",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Idli,_sambar_and_coconut_chutney.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Idli%2C_sambar_and_coconut_chutney.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "idli-sambar.jpg",
    "sourceAssetSha256": "4a948c68dfc2740a4f07f31fa1c7cb1ff54ca50730c54770ba2219cee06e954c",
    "cropPosition": "attention"
  },
  {
    "id": "vada-pav",
    "commonsTitle": "File:Vada Pav-Indian street food.JPG",
    "title": "Vada Pav-Indian street food",
    "author": "Rutvi Mistry",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Vada_Pav-Indian_street_food.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Vada_Pav-Indian_street_food.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "vada-pav.jpg",
    "sourceAssetSha256": "9e4b5c91de23dcd7e3e9ad952e2349443076c35ddb62ec1b59be096f26a51fab",
    "cropPosition": "attention"
  },
  {
    "id": "pav-bhaji",
    "commonsTitle": "File:Pav Bhaji at Home.JPG",
    "title": "Pav Bhaji at Home",
    "author": "Nundhaa",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pav_Bhaji_at_Home.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/06/Pav_Bhaji_at_Home.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "pav-bhaji.jpg",
    "sourceAssetSha256": "c87463f768d855547b454ddc4b312f439bc233c80b2d132d7c0c3267aa44af95",
    "cropPosition": "attention"
  },
  {
    "id": "pani-puri",
    "commonsTitle": "File:Indian cuisine-Panipuri-03.jpg",
    "title": "Indian cuisine-Panipuri-03",
    "author": "Ramakrishna Reddy y",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Indian_cuisine-Panipuri-03.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/22/Indian_cuisine-Panipuri-03.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "pani-puri.jpg",
    "sourceAssetSha256": "bfcc3f71e0ef10ec863bb2bdf280c655fdac68daf077d8308369ed53698bd03b",
    "cropPosition": "attention"
  },
  {
    "id": "samosa",
    "commonsTitle": "File:Samosa (partially open).jpg",
    "title": "Samosa (partially open)",
    "author": "No machine-readable author provided. Zantastik~commonswiki assumed (based on copyright claims).",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Samosa_(partially_open).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/91/Samosa_%28partially_open%29.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "samosa.jpg",
    "sourceAssetSha256": "b35e4a1f0c3425ab47ad45450b7b11c32dc72c83b6644b313f5cbd0aa9793219",
    "cropPosition": "attention"
  },
  {
    "id": "vegetable-pakora",
    "commonsTitle": "File:Pakoras in Jaipur.jpg",
    "title": "Pakoras in Jaipur",
    "author": "ampersandyslexia",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pakoras_in_Jaipur.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Pakoras_in_Jaipur.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "vegetable-pakora.jpg",
    "sourceAssetSha256": "9f9bdc35cc2c08db3cd677d4f28553e60c28842e04bb90cde708bb93b2a5c6b6",
    "cropPosition": "attention"
  },
  {
    "id": "tandoori-chicken",
    "commonsTitle": "File:Tandoori Chicken 1.JPG",
    "title": "Tandoori Chicken 1",
    "author": "Miansari66",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Tandoori_Chicken_1.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Tandoori_Chicken_1.JPG",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "tandoori-chicken.jpg",
    "sourceAssetSha256": "b7d51e626029920866041990fd519e854e53f2849d8f0a47ab5558fbc9762073",
    "cropPosition": "attention"
  },
  {
    "id": "rogan-josh",
    "commonsTitle": "File:Mutton rogan josh.jpg",
    "title": "Mutton rogan josh",
    "author": "stu_spivack",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Mutton_rogan_josh.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/43/Mutton_rogan_josh.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "rogan-josh.jpg",
    "sourceAssetSha256": "f5d446f23f5d2372f0b05a5d60457c2bfa8b55034299338161ac114eccbb1d0b",
    "cropPosition": "attention"
  },
  {
    "id": "goan-fish-curry",
    "commonsTitle": "File:Goan Fish Curry.jpg",
    "title": "Goan Fish Curry",
    "author": "Ramakrishna Reddy y",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Goan_Fish_Curry.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Goan_Fish_Curry.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "goan-fish-curry.jpg",
    "sourceAssetSha256": "d8e2b7cb9dbb3fba13a8262c155f6be38153efa8de592eb1875a0bbf70c1c152",
    "cropPosition": "attention"
  },
  {
    "id": "butter-naan",
    "commonsTitle": "File:ButterNaan.JPG",
    "title": "ButterNaan",
    "author": "Planetvyom",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:ButterNaan.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/86/ButterNaan.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "butter-naan.jpg",
    "sourceAssetSha256": "91df1a4543cb6528efc328372fbd39743acaae67787f1a9c854396b64df58273",
    "cropPosition": "attention"
  },
  {
    "id": "gulab-jamun",
    "commonsTitle": "File:Gulab Jamun served Hot.jpg",
    "title": "Gulab Jamun served Hot",
    "author": "Sibasis21",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gulab_Jamun_served_Hot.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/86/Gulab_Jamun_served_Hot.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "gulab-jamun.jpg",
    "sourceAssetSha256": "a41dba746b2341938dc194cbaf6636ad0f4df05df40ac33c479400ac1810e164",
    "cropPosition": "attention"
  },
  {
    "id": "rice-kheer",
    "commonsTitle": "File:Kheer.jpg",
    "title": "Kheer",
    "author": "stu spivack",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Kheer.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/46/Kheer.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "rice-kheer.jpg",
    "sourceAssetSha256": "146af64de964d9606c77fc2d2496305dfae0fa9870164a18b8a2920a2d520029",
    "cropPosition": "attention"
  }
];

export default indianPhotoCandidates;
