// Generated from pinned, visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-italian-photo-manifest.mjs after an approved source changes.
export const italianPhotoCandidates = [
  {
    "id": "pizza-margherita",
    "commonsTitle": "File:Margherita pizza.jpg",
    "title": "Margherita pizza",
    "author": "Akahito Yamabe",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Margherita_pizza.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Margherita_pizza.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "pizza-margherita.jpg",
    "sourceAssetSha256": "0a903c8fe2f823f36616a8b4f8c82645a2c92b77e26f867929980faff2357d54",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Round Margherita pizza with blistered crust, tomato, melted mozzarella and basil; no unrelated toppings.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "spaghetti-carbonara",
    "commonsTitle": "File:Spaghetti carbonara.jpg",
    "title": "Spaghetti carbonara",
    "author": "Popo le Chien",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Spaghetti_carbonara.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/30/Spaghetti_carbonara.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "spaghetti-carbonara.jpg",
    "sourceAssetSha256": "3001ba3c8043e7309726946fab83da892ba48a4f9c66121d0ce2a8e0da8ed3a4",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Glossy spaghetti carbonara with browned guanciale, cheese and black pepper; no cream-heavy white sauce or vegetable garnish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "cacio-e-pepe",
    "commonsTitle": "File:Cacio e pepe.jpg",
    "title": "Cacio e pepe",
    "author": "Popo le Chien",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Cacio_e_pepe.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/99/Cacio_e_pepe.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "cacio-e-pepe.jpg",
    "sourceAssetSha256": "b13f774faa0290350e06d578795b7ff951192ec784d46767c866c39b9388699e",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Long pasta coated in a pale Pecorino emulsion with abundant black pepper and no tomato or herbs.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bucatini-amatriciana",
    "commonsTitle": "File:Bucatini amatriciana Roma 2019.jpg",
    "title": "Bucatini amatriciana Roma 2019",
    "author": "Blackcat",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bucatini_amatriciana_Roma_2019.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/83/Bucatini_amatriciana_Roma_2019.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "bucatini-amatriciana.jpg",
    "sourceAssetSha256": "806855fe2f085d7d6d2b1b88b021e983d5ed8321d744acf2c882394387226b51",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Bucatini in red tomato sauce with visible guanciale and grated Pecorino; no cream sauce.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pasta-alla-norma",
    "commonsTitle": "File:Pasta alla Norma - Wiki Loves Sicilia.jpg",
    "title": "Pasta alla Norma - Wiki Loves Sicilia",
    "author": "8w9d",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pasta_alla_Norma_-_Wiki_Loves_Sicilia.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Pasta_alla_Norma_-_Wiki_Loves_Sicilia.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "pasta-alla-norma.jpg",
    "sourceAssetSha256": "b5e9202fb31922991e1119ddc55ba514a5e1509a3bb097bab56b3663bce3e477",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Red-sauced pasta with browned eggplant, white grated cheese and basil matching the finished Norma profile.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "trofie-al-pesto",
    "commonsTitle": "File:Trofie al pesto.jpg",
    "title": "Trofie al pesto",
    "author": "Eluinie",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Trofie_al_pesto.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Trofie_al_pesto.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "trofie-al-pesto.jpg",
    "sourceAssetSha256": "59fc43218aa6a175732e21dd25b2400a354885f1ba9bfe773ebd39d4538ebd6c",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Trofie coated in vivid green pesto with the expected Ligurian appearance and no red sauce.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "tagliatelle-ragu-bolognese",
    "commonsTitle": "File:Tagliatelle ragù bolognese 01.jpg",
    "title": "Tagliatelle ragù bolognese 01",
    "author": "https://www.flickr.com/photos/wordridden/",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Tagliatelle_rag%C3%B9_bolognese_01.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Tagliatelle_rag%C3%B9_bolognese_01.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "tagliatelle-ragu-bolognese.jpg",
    "sourceAssetSha256": "c9caae4bb74013de32bd48172086c72412f4bcb4af6c67a84260acb29741d452",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Broad egg-pasta ribbons with a thick finely textured meat ragù and light grated cheese.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "lasagne-bolognese",
    "commonsTitle": "File:Lasagna bolognese1.jpg",
    "title": "Lasagna bolognese1",
    "author": "Schellenberg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Lasagna_bolognese1.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/48/Lasagna_bolognese1.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "lasagne-bolognese.jpg",
    "sourceAssetSha256": "8dea394d5cf6143add621f86a58a9482948c2be477ba154f263abbcc46394639",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Baked lasagne with browned top and distinct pasta, ragù and pale sauce layers.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "risotto-alla-milanese",
    "commonsTitle": "File:Risotto alla milanese.JPG",
    "title": "Risotto alla milanese",
    "author": "Tamorlan",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Risotto_alla_milanese.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Risotto_alla_milanese.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "risotto-alla-milanese.jpg",
    "sourceAssetSha256": "8ab4e7912036261501814a8054e43b384336179e7afb69f83071f6c39246d1a9",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Loose glossy saffron-yellow risotto with distinct rice grains and no heavy garnish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "ossobuco-alla-milanese",
    "commonsTitle": "File:Ossobuco - stu spivack.jpg",
    "title": "Ossobuco - stu spivack",
    "author": "stu_spivack",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ossobuco_-_stu_spivack.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/00/Ossobuco_-_stu_spivack.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "ossobuco-alla-milanese.jpg",
    "sourceAssetSha256": "1cdbfb24537b679983f428102b8feb8391d0bec627cfb868d62f3d9e743ea808",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Single braised cross-cut veal shank with central marrow bone, glossy dark braising sauce and green gremolata; a small noodle side remains visible in the source.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "saltimbocca-alla-romana",
    "commonsTitle": "File:Saltimbocca alla Romana.jpg",
    "title": "Saltimbocca alla Romana",
    "author": "Alec Vuijlsteke",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Saltimbocca_alla_Romana.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/89/Saltimbocca_alla_Romana.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "saltimbocca-alla-romana.jpg",
    "sourceAssetSha256": "30c101abdaf640e83754c3489e1eab5826d4065f3cb7d7a058cab11b5d437984",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Veal cutlets topped with prosciutto and sage in a light pan sauce, matching the Roman presentation.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "melanzane-parmigiana",
    "commonsTitle": "File:Parmigiana di melanzane.jpg",
    "title": "Parmigiana di melanzane",
    "author": "Schellenberg",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Parmigiana_di_melanzane.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/72/Parmigiana_di_melanzane.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "melanzane-parmigiana.jpg",
    "sourceAssetSha256": "f7f870477fa6bcf3796ee4867cec97cc28183a73d02fe8391f68560b55feecb4",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Layered eggplant parmigiana with tomato and browned melted cheese; no pasta layers.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "ribollita",
    "commonsTitle": "File:Ribollita Siena.jpg",
    "title": "Ribollita Siena",
    "author": "Ta4e Negodue",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ribollita_Siena.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Ribollita_Siena.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "ribollita.jpg",
    "sourceAssetSha256": "dc086278b1db9f798b250afea2ce498b2237160f7a8a55d0905c4cb92220f7d7",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Very thick rustic bean-and-vegetable soup with visible bread and greens; the bowl presentation is consistent with ribollita.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "arancini-siciliani",
    "commonsTitle": "File:Arancino Siciliano .jpg",
    "title": "Arancino Siciliano",
    "author": "Enzo Rippa",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Arancino_Siciliano_.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/86/Arancino_Siciliano_.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "arancini-siciliani.jpg",
    "sourceAssetSha256": "93bd86c4cc961fa088c1a656dff3e5888d568732ec58561b885c93aea51ffe65",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Deep-golden Sicilian rice balls with a crisp crumb exterior and visible filled centre.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "focaccia-genovese",
    "commonsTitle": "File:Focaccia genovese su tagliere in legno, 1.jpg",
    "title": "Focaccia genovese su tagliere in legno, 1",
    "author": "Own work",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Focaccia_genovese_su_tagliere_in_legno,_1.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Focaccia_genovese_su_tagliere_in_legno%2C_1.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "focaccia-genovese.jpg",
    "sourceAssetSha256": "046284a0acd4a8b2f1ca2bfcc5d5aefacd932bef829610bd1fb6ba89632c241e",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Golden rectangular focaccia with deep dimples and an olive-oil sheen.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "spaghetti-alle-vongole",
    "commonsTitle": "File:Spaghetti alle vongole.jpg",
    "title": "Spaghetti alle vongole",
    "author": "Flickr user: [2] , retouched by AM",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Spaghetti_alle_vongole.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/70/Spaghetti_alle_vongole.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "spaghetti-alle-vongole.jpg",
    "sourceAssetSha256": "4b7aab70481930aaeded7dd50833ad746676362806bf8e2ed2c4853e80bd1d20",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Spaghetti with open clam shells and a pale glossy briny sauce; no tomato or cheese.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pollo-alla-cacciatora",
    "commonsTitle": "File:Chicken cacciatore (13759100).jpg",
    "title": "Chicken cacciatore (13759100)",
    "author": "Charles Haynes",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Chicken_cacciatore_(13759100).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Chicken_cacciatore_%2813759100%29.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "pollo-alla-cacciatora.jpg",
    "sourceAssetSha256": "411099e5289e902fbe60d592e0fc84349ff9e61b181450b72002fe295f01839f",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Chicken pieces in a rustic tomato braise with vegetables, matching cacciatora rather than a cream sauce.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "tiramisu",
    "commonsTitle": "File:Tiramisu - Raffaele Diomede.jpg",
    "title": "Tiramisu - Raffaele Diomede",
    "author": "Raffaele Diomede from Pordenone, ITALIA",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Tiramisu_-_Raffaele_Diomede.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/58/Tiramisu_-_Raffaele_Diomede.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "tiramisu.jpg",
    "sourceAssetSha256": "f69be190457230612327f6db5e70acfc279ae50a284b1cf1ae273f4a0cb79e1e",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Clean square tiramisu slice with two coffee-darkened biscuit layers, pale mascarpone layers and an even cocoa top.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "panna-cotta",
    "commonsTitle": "File:Panna cotta 02.jpg",
    "title": "Panna cotta 02",
    "author": "Arnaud 25",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Panna_cotta_02.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Panna_cotta_02.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "panna-cotta.jpg",
    "sourceAssetSha256": "537872a7a216ae9a821605efd363db658f3041d3a87e98704132105ba99ad1a5",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Smooth pale panna cotta is clearly visible in a simple glass; the Commons source includes a red fruit sauce layer that is absent from this recipe's preferred plain presentation.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "cannoli-siciliani",
    "commonsTitle": "File:Cannoli siciliani.jpg",
    "title": "Cannoli siciliani",
    "author": "Stefano Mortellaro from Catania, Italy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Cannoli_siciliani.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/99/Cannoli_siciliani.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "cannoli-siciliani.jpg",
    "sourceAssetSha256": "ebd0ee33db25f700390be704b25bf7f0c642a95f68d5fbaf64b6ff4f8a05d2be",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Crisp blistered cannoli shells filled with pale ricotta cream and dark chocolate pieces.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "cantucci",
    "commonsTitle": "File:Biscotti - cantucci.jpg",
    "title": "Biscotti - cantucci",
    "author": "VD",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Biscotti_-_cantucci.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/b4/Biscotti_-_cantucci.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "cantucci.jpg",
    "sourceAssetSha256": "af9fe3d8e6aa69ce0f4f431d4e18f9d736003019a92e82ccbd2c3c706b7c4e90",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Dry golden Tuscan almond biscuits with visible almond cross-sections and no chocolate coating.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  }
];

export default italianPhotoCandidates;
