// Generated from pinned, visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-mediterranean-photo-manifest.mjs after an approved source changes.
export const mediterraneanPhotoCandidates = [
  {
    "id": "bouillabaisse",
    "commonsTitle": "File:Bouillabaisse, provansalska riblja juha.jpg",
    "title": "Bouillabaisse, provansalska riblja juha.jpg",
    "author": "August Dominus",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bouillabaisse,_provansalska_riblja_juha.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Bouillabaisse%2C_provansalska_riblja_juha.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "bouillabaisse.jpg",
    "sourceAssetSha256": "5b969fb7a2d1b994db49e14e8c48cc61e72bb39aee1f9dac34e12107c677d6c7",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A serving of Provençal fish stew with fish and seafood in saffron-tomato broth.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pissaladiere",
    "commonsTitle": "File:Pissaladière 01.jpg",
    "title": "Pissaladière 01.jpg",
    "author": "Arnaud 25",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pissaladi%C3%A8re_01.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Pissaladi%C3%A8re_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "pissaladiere.jpg",
    "sourceAssetSha256": "3fe78917be3af11d8858a0127f0edfb072eee71cddcbb132598aff339efebc26",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A finished Niçoise pissaladière topped with slowly cooked onions, anchovies and olives.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "caponata",
    "commonsTitle": "File:Caponata (23791306323).jpg",
    "title": "Caponata (23791306323).jpg",
    "author": "Luca Nebuloni from Milan, Italy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Caponata_(23791306323).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/49/Caponata_%2823791306323%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "caponata.jpg",
    "sourceAssetSha256": "9707001577653f2dfdc418ee4d128fb1b40ff4e9c8c8f8ffef042e6a6de14930",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Sicilian sweet-sour eggplant caponata is the clear subject.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pasta-con-le-sarde",
    "commonsTitle": "File:Pasta con le sarde.jpg",
    "title": "Pasta con le sarde.jpg",
    "author": "Sebastian Fischer",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pasta_con_le_sarde.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/58/Pasta_con_le_sarde.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceAsset": "pasta-con-le-sarde.jpg",
    "sourceAssetSha256": "9727396ec43154b6f907e6a11d83615f80242203b63e0c49939d866edbb29170",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Sicilian pasta with sardines and fennel is served as a finished dish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "brik-a-loeuf",
    "commonsTitle": "File:Fried brik.jpg",
    "title": "Fried brik.jpg",
    "author": "Meriemou",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Fried_brik.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Fried_brik.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "brik-a-loeuf.jpg",
    "sourceAssetSha256": "d4bebf474973dd2460fbaf5f1d03d65959410a7869d4b2099e57f8f14ed84915",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A freshly fried Tunisian brik with crisp folded pastry is shown as the finished dish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "lablabi",
    "commonsTitle": "File:Lablabi.jpg",
    "title": "Lablabi.jpg",
    "author": "Drmaik",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Lablabi.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Lablabi.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "lablabi.jpg",
    "sourceAssetSha256": "8d67c4e0472a094b4fcd7f72dd05f5664b0e1bb50a64f9f10dc9a7853cb7f6b5",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A bowl of Tunisian chickpea stew ready to eat in a restaurant in Tunis.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "harira",
    "commonsTitle": "File:Harira..JPG",
    "title": "Harira..JPG",
    "author": "Miansari66",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Harira..JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Harira..JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "harira.jpg",
    "sourceAssetSha256": "04e2251f016dd035049f9721dba8de4ceb27da7bd9a70d475ea8cfb0053655fe",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "A bowl of Moroccan harira with chickpeas, lentils and herbs.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "zaalouk",
    "commonsTitle": "File:Zaalouk 01.jpg",
    "title": "Zaalouk 01.jpg",
    "author": "Arnaud 25",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Zaalouk_01.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/59/Zaalouk_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "zaalouk.jpg",
    "sourceAssetSha256": "0b61560214d5b3e96522ba3477dd7cb6ef2944cbd857ae40919a9c7bc85240fe",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Moroccan zaalouk, a cooked eggplant and tomato salad, served as a finished dish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "imam-bayildi",
    "commonsTitle": "File:A plate of imambayildi.jpg",
    "title": "A plate of imambayildi.jpg",
    "author": "E4024",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:A_plate_of_imambayildi.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/22/A_plate_of_imambayildi.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "imam-bayildi.jpg",
    "sourceAssetSha256": "8136ce8459485909872fec94f99b35ddd1fff90b914427685bfa050046d933c7",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Turkish imam bayildi eggplants are presented on a serving plate.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "gozleme",
    "commonsTitle": "File:Gozleme at Manning Market.jpg",
    "title": "Gozleme at Manning Market.jpg",
    "author": "Orderinchaos",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gozleme_at_Manning_Market.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/1/17/Gozleme_at_Manning_Market.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "gozleme.jpg",
    "sourceAssetSha256": "85899aa930125553179248b9525fb3c70c978fae936c53e8375823e1a9411646",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Folded Turkish gozleme pieces with browned griddle marks and visible green filling are plated as the finished dish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "halloumi-saganaki",
    "commonsTitle": "File:Grilled Halloumi.jpg",
    "title": "Grilled Halloumi.jpg",
    "author": "Hmioannou",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Grilled_Halloumi.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/30/Grilled_Halloumi.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceAsset": "halloumi-saganaki.jpg",
    "sourceAssetSha256": "7717da50b9c3dddd4d06b2ff789210966690067f138c598aeee6702877517170",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Grilled halloumi cheese with a browned surface, suitable as a pan-seared halloumi reference.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "crni-rizot",
    "commonsTitle": "File:Crni Rizoto - Pizzeria Desetka (14848569142).jpg",
    "title": "Crni Rizoto - Pizzeria Desetka (14848569142).jpg",
    "author": "Haydn Blackey from Cardiff, Wales",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Crni_Rizoto_-_Pizzeria_Desetka_(14848569142).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/28/Crni_Rizoto_-_Pizzeria_Desetka_%2814848569142%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "crni-rizot.jpg",
    "sourceAssetSha256": "10a8df03dda6b3233c2cc179bfdcfa82c70f977e011b8162dd9d51e46053daae",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Croatian black risotto with cuttlefish ink and seafood.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "stuffat-tal-fenek",
    "commonsTitle": "File:The national dish of Malta – Stuffat tal-Fenek (rabbit stew).jpg",
    "title": "The national dish of Malta – Stuffat tal-Fenek (rabbit stew).jpg",
    "author": "Renata Apan",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:The_national_dish_of_Malta_%E2%80%93_Stuffat_tal-Fenek_(rabbit_stew).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/82/The_national_dish_of_Malta_%E2%80%93_Stuffat_tal-Fenek_%28rabbit_stew%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "stuffat-tal-fenek.jpg",
    "sourceAssetSha256": "28489720e6611a680c860c72f7fc13c3cd34e6ec2e4cbcbd178bbc3f5a4b85d6",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-20",
    "reviewNote": "Maltese rabbit stew is shown as a finished tomato-based braise.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  }
];

export default mediterraneanPhotoCandidates;
