export const recipeUi = {
  en: {
    collectionEyebrow: "Curated Chinese cooking",
    collectionTitle: "Chinese recipes for real kitchens",
    collectionIntro: "Choose a dish, then open its complete recipe. Every published entry is cross-checked against multiple cooking references and paired only with a commercially reusable real photograph that passed a manual visual-match review.",
    recipeCount: "{count} recipes published",
    viewRecipe: "Open recipe",
    recipeEyebrow: "Chinese recipe",
    prep: "Prep",
    cook: "Cook",
    total: "Total",
    servings: "Servings",
    minutes: "{count}\u00a0min",
    hours: "{count}\u00a0hr",
    hoursMinutes: "{hours}\u00a0hr {minutes}\u00a0min",
    ingredients: "Ingredients",
    instructions: "Method",
    practicalNotes: "Practical notes",
    tips: "Tips",
    commonMistakes: "Common mistakes",
    substitutions: "Substitutions",
    storage: "Storage",
    culturalNotes: "Cultural context",
    sourcesCredits: "Sources and photo credit",
    recipeSources: "Recipe references",
    photoCredit: "Real finished-dish photograph",
    photoBy: "Photograph by {author}",
    sourcePage: "Source page",
    originalFile: "Original file",
    modified: "Cropped, resized, and compressed by Recipe Nest Vault.",
    methodNote: "This standardized method was independently rewritten after cross-checking the references below. Recipe Nest Vault does not claim that the credited photographer cooked from this exact version.",
    backToCollection: "Back to Chinese recipes",
    relatedRecipes: "More Chinese recipes",
    noApprovedRecipes: "No recipe is published until both its method and real photograph pass review."
  },
  "zh-hant": {
    collectionEyebrow: "精選中華料理",
    collectionTitle: "真正能在家中完成的中華食譜",
    collectionIntro: "先選擇料理，再進入完整食譜頁。每道公開食譜都會交叉核對多個料理來源，並且只搭配經人工確認與成品吻合、可商用的真實照片。",
    recipeCount: "已公開 {count} 道食譜",
    viewRecipe: "查看食譜",
    recipeEyebrow: "中華料理食譜",
    prep: "備料",
    cook: "烹調",
    total: "總時間",
    servings: "份量",
    minutes: "{count}\u00a0分鐘",
    hours: "{count}\u00a0小時",
    hoursMinutes: "{hours}\u00a0小時 {minutes}\u00a0分鐘",
    ingredients: "食材",
    instructions: "作法",
    practicalNotes: "實用提醒",
    tips: "成功要點",
    commonMistakes: "常見錯誤",
    substitutions: "替代方案",
    storage: "保存方式",
    culturalNotes: "料理文化",
    sourcesCredits: "資料來源與照片授權",
    recipeSources: "食譜參考來源",
    photoCredit: "真實成品實拍",
    photoBy: "攝影：{author}",
    sourcePage: "原始頁面",
    originalFile: "原始檔案",
    modified: "Recipe Nest Vault 已裁切、調整尺寸並壓縮。",
    methodNote: "本站交叉核對下列來源後，重新整理為這份標準化作法；不會宣稱授權照片的攝影者使用了本站這一份配方。",
    backToCollection: "返回中華料理食譜",
    relatedRecipes: "更多中華料理",
    noApprovedRecipes: "配方與真實照片尚未同時通過稽核前，不會公開該食譜。"
  },
  ja: {
    collectionEyebrow: "厳選した中国料理",
    collectionTitle: "家庭で再現しやすい中国料理レシピ",
    collectionIntro: "料理を選ぶと、詳しいレシピページに進めます。公開するレシピは複数の料理資料を照合し、完成形との一致を人の目で確認した、商用利用可能な実写写真だけを掲載します。",
    recipeCount: "{count}件のレシピを公開中",
    viewRecipe: "レシピを見る",
    recipeEyebrow: "中国料理レシピ",
    prep: "下準備",
    cook: "調理",
    total: "合計",
    servings: "分量",
    minutes: "{count}分",
    hours: "{count}時間",
    hoursMinutes: "{hours}時間{minutes}分",
    ingredients: "材料",
    instructions: "作り方",
    practicalNotes: "実用メモ",
    tips: "コツ",
    commonMistakes: "よくある失敗",
    substitutions: "代替材料",
    storage: "保存",
    culturalNotes: "料理の背景",
    sourcesCredits: "参考資料と写真クレジット",
    recipeSources: "レシピの参考資料",
    photoCredit: "完成料理の実写写真",
    photoBy: "撮影：{author}",
    sourcePage: "出典ページ",
    originalFile: "元のファイル",
    modified: "Recipe Nest Vault がトリミング、リサイズ、圧縮を行いました。",
    methodNote: "以下の資料を照合し、独自に整理した標準化レシピです。写真の撮影者がこのレシピで調理したとは表示しません。",
    backToCollection: "中国料理レシピに戻る",
    relatedRecipes: "ほかの中国料理",
    noApprovedRecipes: "レシピと実写写真の両方が審査を通るまで公開しません。"
  },
  ko: {
    collectionEyebrow: "엄선한 중화요리",
    collectionTitle: "집에서 재현하기 쉬운 중화요리 레시피",
    collectionIntro: "요리를 고르면 전체 레시피 페이지로 이동합니다. 공개 레시피는 여러 조리 자료를 교차 확인하고, 완성 모습과 일치하는지 직접 검토한 상업적 이용 가능 실사 사진만 사용합니다.",
    recipeCount: "레시피 {count}개 공개",
    viewRecipe: "레시피 보기",
    recipeEyebrow: "중화요리 레시피",
    prep: "준비",
    cook: "조리",
    total: "총시간",
    servings: "분량",
    minutes: "{count}분",
    hours: "{count}시간",
    hoursMinutes: "{hours}시간 {minutes}분",
    ingredients: "재료",
    instructions: "만드는 법",
    practicalNotes: "실용 메모",
    tips: "성공 요령",
    commonMistakes: "흔한 실수",
    substitutions: "대체 재료",
    storage: "보관",
    culturalNotes: "요리 배경",
    sourcesCredits: "자료 출처와 사진 크레딧",
    recipeSources: "레시피 참고 자료",
    photoCredit: "완성 요리 실사 사진",
    photoBy: "촬영: {author}",
    sourcePage: "출처 페이지",
    originalFile: "원본 파일",
    modified: "Recipe Nest Vault에서 자르고 크기를 조정한 뒤 압축했습니다.",
    methodNote: "아래 자료를 교차 확인한 뒤 독자적으로 정리한 표준화 조리법입니다. 사진가가 이 정확한 레시피로 조리했다고 표시하지 않습니다.",
    backToCollection: "중화요리 레시피로 돌아가기",
    relatedRecipes: "다른 중화요리",
    noApprovedRecipes: "레시피와 실사 사진이 모두 검토를 통과하기 전에는 공개하지 않습니다."
  },
  th: {
    collectionEyebrow: "อาหารจีนที่คัดสรร",
    collectionTitle: "สูตรอาหารจีนที่ทำซ้ำได้ในครัวจริง",
    collectionIntro: "เลือกเมนูแล้วเปิดหน้าสูตรฉบับเต็ม ทุกสูตรที่เผยแพร่ผ่านการตรวจสอบกับแหล่งข้อมูลการทำอาหารหลายแห่ง และใช้เฉพาะภาพถ่ายจริงที่อนุญาตให้ใช้เชิงพาณิชย์และผ่านการตรวจเทียบกับหน้าตาอาหารด้วยคน",
    recipeCount: "เผยแพร่แล้ว {count} สูตร",
    viewRecipe: "ดูสูตร",
    recipeEyebrow: "สูตรอาหารจีน",
    prep: "เตรียม",
    cook: "ปรุง",
    total: "รวม",
    servings: "จำนวนเสิร์ฟ",
    minutes: "{count}\u00a0นาที",
    hours: "{count}\u00a0ชม.",
    hoursMinutes: "{hours}\u00a0ชม. {minutes}\u00a0นาที",
    ingredients: "วัตถุดิบ",
    instructions: "วิธีทำ",
    practicalNotes: "คำแนะนำใช้งานจริง",
    tips: "เคล็ดลับ",
    commonMistakes: "ข้อผิดพลาดที่พบบ่อย",
    substitutions: "วัตถุดิบทดแทน",
    storage: "การเก็บรักษา",
    culturalNotes: "บริบทของอาหาร",
    sourcesCredits: "แหล่งข้อมูลและเครดิตภาพ",
    recipeSources: "แหล่งอ้างอิงสูตร",
    photoCredit: "ภาพถ่ายจริงของอาหารที่เสร็จแล้ว",
    photoBy: "ภาพถ่ายโดย {author}",
    sourcePage: "หน้าต้นฉบับ",
    originalFile: "ไฟล์ต้นฉบับ",
    modified: "Recipe Nest Vault ครอป ปรับขนาด และบีบอัดภาพ",
    methodNote: "เราเรียบเรียงวิธีมาตรฐานนี้ขึ้นใหม่หลังตรวจสอบแหล่งข้อมูลด้านล่างหลายแห่ง และไม่กล่าวอ้างว่าช่างภาพทำอาหารจากสูตรฉบับนี้โดยตรง",
    backToCollection: "กลับไปสูตรอาหารจีน",
    relatedRecipes: "สูตรอาหารจีนเพิ่มเติม",
    noApprovedRecipes: "เราจะไม่เผยแพร่จนกว่าสูตรและภาพถ่ายจริงจะผ่านการตรวจสอบทั้งคู่"
  }
};
