// Generated from pinned, visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-spanish-photo-manifest.mjs after an approved source changes.
export const spanishPhotoCandidates = [
  {
    "id": "paella-valenciana",
    "commonsTitle": "File:Paella valenciana 01.jpg",
    "title": "Paella valenciana 01",
    "author": "Dorieo",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Paella_valenciana_01.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/1/12/Paella_valenciana_01.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "paella-valenciana.jpg",
    "sourceAssetSha256": "21ba611f4b28f56b87721b936f26e855307d979b9597fadb5542cbd2ddebf05e",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Wide Valencian paella with a thin saffron rice layer and visible traditional meat and bean components; minor lemon garnish is acceptable.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "tortilla-espanola",
    "commonsTitle": "File:Tortilla española-MMS.JPG",
    "title": "Tortilla española-MMS",
    "author": "Tamorlan",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Tortilla_espa%C3%B1ola-MMS.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/95/Tortilla_espa%C3%B1ola-MMS.JPG",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceAsset": "tortilla-espanola.jpg",
    "sourceAssetSha256": "46590eeb9e80811440e3e28a7a9bf276249853129e0de12f9b3ecb57ce8323c3",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Thick golden potato tortilla with a cut wedge showing layered potato and set egg.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "gazpacho-andaluz",
    "commonsTitle": "File:Gazpacho in a white bowl.jpg",
    "title": "Gazpacho in a white bowl",
    "author": "E4024",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gazpacho_in_a_white_bowl.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/c/c3/Gazpacho_in_a_white_bowl.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "gazpacho-andaluz.jpg",
    "sourceAssetSha256": "29566011332aa67b02c4ff5b2b5f8df0e0337b65e6a6b3d095baf80c576a64f1",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Smooth bright-red chilled gazpacho in a simple white bowl with only a restrained garnish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "salmorejo-cordobes",
    "commonsTitle": "File:Salmorejo 201207.jpg",
    "title": "Salmorejo 201207",
    "author": "Tirithel",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Salmorejo_201207.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/1/18/Salmorejo_201207.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "salmorejo-cordobes.jpg",
    "sourceAssetSha256": "6609f1423e143c96315c35e437ade5e81db7c3351137d63bdb3d726bbe47d902",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Dense orange-red salmorejo topped with chopped egg and cured-ham garnish in a shallow bowl.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "patatas-bravas",
    "commonsTitle": "File:Patatas bravas-Lavapies.jpg",
    "title": "Patatas bravas-Lavapies",
    "author": "Tamorlan",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Patatas_bravas-Lavapies.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Patatas_bravas-Lavapies.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceAsset": "patatas-bravas.jpg",
    "sourceAssetSha256": "dc3320a0cfbfb2af29d7510edd53eb27aaf094dd4e25e47d80fdf60b42ad26ca",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Deep-golden potato pieces topped with brick-red brava sauce, matching the crisp tapas presentation.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "croquetas-de-jamon",
    "commonsTitle": "File:20250720 Croquetas jamón at Restaurant O Poleiro in Combarro anagoria.jpg",
    "title": "20250720 Croquetas jamón at Restaurant O Poleiro in Combarro anagoria",
    "author": "Anagoria",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:20250720_Croquetas_jam%C3%B3n_at_Restaurant_O_Poleiro_in_Combarro_anagoria.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/ab/20250720_Croquetas_jam%C3%B3n_at_Restaurant_O_Poleiro_in_Combarro_anagoria.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "croquetas-de-jamon.jpg",
    "sourceAssetSha256": "236a39d62f5fef709d47a9a49cd795ec9d26a57ab065cf414a3e5d11abd83ba5",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Small uniformly deep-golden ham croquettes with a fine crisp crumb shell.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "gambas-al-ajillo",
    "commonsTitle": "File:Gambas al ajillo, 2024.jpg",
    "title": "Gambas al ajillo, 2024",
    "author": "Juan Emilio Prades Bel",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gambas_al_ajillo,_2024.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Gambas_al_ajillo%2C_2024.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceAsset": "gambas-al-ajillo.jpg",
    "sourceAssetSha256": "6fe30e4ccf4554d8020d3b2a66571b6fd5f430c0a81f9f7513a3fed708af0d5b",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Pink prawns in abundant glossy garlic olive oil with visible garlic and herb flecks; no tomato or cream sauce.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pan-con-tomate",
    "commonsTitle": "File:Pa amb tomaquet.jpg",
    "title": "Pa amb tomaquet",
    "author": "Jennifer Woodard Maderazo",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pa_amb_tomaquet.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Pa_amb_tomaquet.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "pan-con-tomate.jpg",
    "sourceAssetSha256": "d6ae0ef5184bb491b74462069d611de06fbfc5634dea377520efc8ad5e5c7eff",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Rustic toasted bread covered with grated ripe tomato and olive-oil sheen.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "fideua",
    "commonsTitle": "File:Fideuà.jpg",
    "title": "Fideuà",
    "author": "Aidafuste",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Fideu%C3%A0.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/77/Fideu%C3%A0.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "fideua.jpg",
    "sourceAssetSha256": "9ed22db2af319f76fbdc9531aca412609b2a061a38fbdd946fa3e7da5424252f",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Mostly dry short fideua noodles in a wide plated serving with visible seafood and saffron-red tone.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "cocido-madrileno",
    "commonsTitle": "File:Cocido madrileño.jpg",
    "title": "Cocido madrileño",
    "author": "Smnt",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Cocido_madrile%C3%B1o.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/55/Cocido_madrile%C3%B1o.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "cocido-madrileno.jpg",
    "sourceAssetSha256": "0bf664554c0f055df277826695053b198b5f50abae36c0986e3add6d30e5f9de",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Cocido served in separated courses with broth apart from chickpeas, vegetables and meats; source shows a traditional two-vuelco service rather than all three separately.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "fabada-asturiana",
    "commonsTitle": "File:Fabada en cazuela de barro.jpg",
    "title": "Fabada en cazuela de barro",
    "author": "Juan J. Martínez from Valencia, España",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Fabada_en_cazuela_de_barro.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/77/Fabada_en_cazuela_de_barro.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "fabada-asturiana.jpg",
    "sourceAssetSha256": "8054f14c84cb2a05b710e1866b23fd917a74100a538f0df6477f55b3fee3b42e",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Large creamy white beans in a rustic earthenware bowl with chorizo, morcilla and cured pork pieces.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pulpo-a-la-gallega",
    "commonsTitle": "File:Polbo a feira.jpg",
    "title": "Polbo a feira",
    "author": "Freecat (José Antonio Gil Martínez) from Vigo , Galicia",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Polbo_a_feira.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/78/Polbo_a_feira.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "pulpo-a-la-gallega.jpg",
    "sourceAssetSha256": "5bc20f5d6863c9577844d7cbd37c1355011f49ed554f40a7dc2544aed86efdac",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Thick octopus coins on a simple plate with paprika, coarse salt and olive-oil sheen.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bacalao-al-pil-pil",
    "commonsTitle": "File:Bacalao pilpil 1.jpg",
    "title": "Bacalao pilpil 1",
    "author": "Ardo Beltz",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bacalao_pilpil_1.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/b0/Bacalao_pilpil_1.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceAsset": "bacalao-al-pil-pil.jpg",
    "sourceAssetSha256": "addb2f29bcdc8da6b50d21baa43b03fbf8a7573057446139b2a7533f345ddd10",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Salt cod pieces in a glossy pale-golden pil-pil emulsion with no tomato or cream.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pisto-manchego",
    "commonsTitle": "File:Pisto con huevos.jpg",
    "title": "Pisto con huevos",
    "author": "El Mono Español",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pisto_con_huevos.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Pisto_con_huevos.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "pisto-manchego.jpg",
    "sourceAssetSha256": "f89dabebfd09012cb8a06512f3d757c07dd80b68dcb118e5ea5982190e3958c9",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Thick red-orange vegetable pisto with clearly visible diced vegetables and fried eggs, no rice side.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "marmitako",
    "commonsTitle": "File:Marmitako de atún (España).jpg",
    "title": "Marmitako de atún (España)",
    "author": "Juan Emilio Prades Bel",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Marmitako_de_at%C3%BAn_(Espa%C3%B1a).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Marmitako_de_at%C3%BAn_%28Espa%C3%B1a%29.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "marmitako.jpg",
    "sourceAssetSha256": "b1580a25c28eeb2bf8d9e26c0679e4cbfa44bc2ffb817e4b802a837f57bd9840",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Clean close-up of tuna chunks and potatoes in a red-golden Basque marmitako broth with no people or event setting.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "calamares-a-la-romana",
    "commonsTitle": "File:Calamares a la Romana-2009.jpg",
    "title": "Calamares a la Romana-2009",
    "author": "Tamorlan",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Calamares_a_la_Romana-2009.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/1/17/Calamares_a_la_Romana-2009.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceAsset": "calamares-a-la-romana.jpg",
    "sourceAssetSha256": "170d47df6d2677f08c8bbc43d631fba272bf71bed3378f54496c4a8ccd75ab15",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Distinct squid rings in a thin evenly golden batter served with lemon, without breadcrumb crust or sauce.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "churros-con-chocolate",
    "commonsTitle": "File:Chocolate con churros - San Ginés - Madrid.jpg",
    "title": "Chocolate con churros - San Ginés - Madrid",
    "author": "w:es:Usuario:Barcex",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Chocolate_con_churros_-_San_Gin%C3%A9s_-_Madrid.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/22/Chocolate_con_churros_-_San_Gin%C3%A9s_-_Madrid.jpg",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceAsset": "churros-con-chocolate.jpg",
    "sourceAssetSha256": "7d60f26ad647fdbdb123f351b604ccdb63dda0e1cae2d5c43a81e1318dea5d1c",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Long ridged golden churros beside a small cup of thick dark Spanish drinking chocolate.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "crema-catalana",
    "commonsTitle": "File:Crema Catalana (7 Portes).jpg",
    "title": "Crema Catalana (7 Portes)",
    "author": "Tamorlan",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Crema_Catalana_(7_Portes).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/45/Crema_Catalana_%287_Portes%29.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceAsset": "crema-catalana.jpg",
    "sourceAssetSha256": "39dcf4e258759bea11b1fabb53cf1b77c304a648db08f62a05b41af1157521e2",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Shallow terracotta crema catalana with a thin evenly burnt amber sugar crust.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "tarta-de-santiago",
    "commonsTitle": "File:Tarta de Santiago.jpg",
    "title": "Tarta de Santiago",
    "author": "No machine-readable author provided. Poniol60 assumed (based on copyright claims).",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Tarta_de_Santiago.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Tarta_de_Santiago.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceAsset": "tarta-de-santiago.jpg",
    "sourceAssetSha256": "83ba1e1155bf13364d037300f68084264b57844ca041f219ee527e8469d83ab1",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Low round almond cake dusted with icing sugar and a clear Cross of Saint James silhouette.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "arroz-con-leche",
    "commonsTitle": "File:Arros amb llet.jpg",
    "title": "Arros amb llet",
    "author": "Slastic",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Arros_amb_llet.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/66/Arros_amb_llet.jpg",
    "license": "Public Domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Licensing",
    "sourceAsset": "arroz-con-leche.jpg",
    "sourceAssetSha256": "e09a4210a3fd1272a8c71603bf7a7dbe140415afd247e5860cdb26a80a0b107e",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-13",
    "reviewNote": "Creamy rice pudding in terracotta with an even cinnamon dusting matching the revised traditional finish.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  }
];

export default spanishPhotoCandidates;
