// Generated from visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-taiwanese-photo-manifest.mjs after an approved source changes.
export const taiwanesePhotoCandidates = [
  {
    "id": "taiwanese-beef-noodle-soup",
    "commonsTitle": "File:Taiwanese Beef Noodle Soup.jpg",
    "title": "Taiwanese Beef Noodle Soup",
    "author": "Jjj84206",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Taiwanese_Beef_Noodle_Soup.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/d/d8/Taiwanese_Beef_Noodle_Soup.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "taiwanese-beef-noodle-soup.jpg",
    "sourceAssetSha256": "347358922402b3259d0277d6c7fec3a147385ab064f7df91594de39b89776135",
    "cropPosition": "attention"
  },
  {
    "id": "lu-rou-fan",
    "commonsTitle": "File:Lurou fan(Taiwanese cuisine).jpg",
    "title": "Lurou fan(Taiwanese cuisine)",
    "author": "Jzest",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Lurou_fan(Taiwanese_cuisine).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Lurou_fan%28Taiwanese_cuisine%29.jpg",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "lu-rou-fan.jpg",
    "sourceAssetSha256": "201871560ff59b78773afbfc90c546c14ae0c0bc8b1f305de7267cd023895d6b",
    "cropPosition": "attention"
  },
  {
    "id": "three-cup-chicken",
    "commonsTitle": "File:Sanbeiji.jpg",
    "title": "Sanbeiji",
    "author": "Archon6812",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Sanbeiji.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/50/Sanbeiji.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "three-cup-chicken.jpg",
    "sourceAssetSha256": "9e563adc251297f94f74bb76edd056a1bec8dd6495e9e7d81eadd9641a3bc512",
    "cropPosition": "attention"
  },
  {
    "id": "oyster-omelette",
    "commonsTitle": "File:Oyster omelette by Adonis Chen in Tainan City.jpg",
    "title": "Oyster omelette by Adonis Chen in Tainan City",
    "author": "Adonis Chen from Tainan, Taiwan",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Oyster_omelette_by_Adonis_Chen_in_Tainan_City.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/78/Oyster_omelette_by_Adonis_Chen_in_Tainan_City.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "oyster-omelette.jpg",
    "sourceAssetSha256": "9fced09577d03e8889bb9c58aa85db6c2facf6c24c88de86abe76a92742b7f92",
    "cropPosition": "attention"
  },
  {
    "id": "taiwanese-popcorn-chicken",
    "commonsTitle": "File:TWBC Taiwanese fried chicken 20070303.jpg",
    "title": "TWBC Taiwanese fried chicken 20070303",
    "author": "JeanHavoc",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:TWBC_Taiwanese_fried_chicken_20070303.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/71/TWBC_Taiwanese_fried_chicken_20070303.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "taiwanese-popcorn-chicken.jpg",
    "sourceAssetSha256": "c1960f37ab03e915a8b0a808c55ed353d7dfa61091f5d3a9df9be91ffbb8a396",
    "cropPosition": "attention"
  },
  {
    "id": "gua-bao",
    "commonsTitle": "File:Gua-bao by the Yuan Fang Guabao at Huaxi Street 2023-04-28 01.jpg",
    "title": "Gua-bao by the Yuan Fang Guabao at Huaxi Street 2023-04-28 01",
    "author": "Wang Yu Ching / Office of the President, ROC (Taiwan) (中華民國總統府)",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Gua-bao_by_the_Yuan_Fang_Guabao_at_Huaxi_Street_2023-04-28_01.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Gua-bao_by_the_Yuan_Fang_Guabao_at_Huaxi_Street_2023-04-28_01.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "gua-bao.jpg",
    "sourceAssetSha256": "e341b8db5866d068e6c327309206f579478357defbb230b910abc12cc0c3b805",
    "cropPosition": "east"
  },
  {
    "id": "dan-bing",
    "commonsTitle": "File:Dan Bing (Taiwanese egg crepe).jpg",
    "title": "Dan Bing (Taiwanese egg crepe)",
    "author": "Joy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Dan_Bing_(Taiwanese_egg_crepe).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/d/d8/Dan_Bing_%28Taiwanese_egg_crepe%29.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "dan-bing.jpg",
    "sourceAssetSha256": "9a9374d67150414917743c31649a7a75c69f1bd7644127e4874d092c025ddc4b",
    "cropPosition": "attention"
  },
  {
    "id": "chiayi-turkey-rice",
    "commonsTitle": "File:Chiayi turkey pilaf.jpg",
    "title": "Chiayi turkey pilaf",
    "author": "Neville Wang",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Chiayi_turkey_pilaf.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/75/Chiayi_turkey_pilaf.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "chiayi-turkey-rice.jpg",
    "sourceAssetSha256": "df8bbf77f2da25e3ebcbb86f8521c4d4fddbd6514eaff0638732303b073aee59",
    "cropPosition": "attention"
  },
  {
    "id": "danzai-noodles",
    "commonsTitle": "File:Tan Tsai Noodle of Tu Hsiao Yue 2015.jpg",
    "title": "Tan Tsai Noodle of Tu Hsiao Yue 2015",
    "author": "Wpcpey",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Tan_Tsai_Noodle_of_Tu_Hsiao_Yue_2015.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/71/Tan_Tsai_Noodle_of_Tu_Hsiao_Yue_2015.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "danzai-noodles.jpg",
    "sourceAssetSha256": "40300ac72058c5b67d95259e1df49641b247386f49adc7b547649c3d0fb1150f",
    "cropPosition": "attention"
  },
  {
    "id": "ba-wan",
    "commonsTitle": "File:Bawan umiao.jpg",
    "title": "Bawan umiao",
    "author": "Takoradee",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bawan_umiao.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Bawan_umiao.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "ba-wan.jpg",
    "sourceAssetSha256": "16061a63a45b3331d0a5a8da8f574a186289cc7058a3691c6c7c75762b548650",
    "cropPosition": "attention"
  },
  {
    "id": "pork-ball-rice-vermicelli-soup",
    "commonsTitle": "File:貢丸米粉湯.jpg",
    "title": "貢丸米粉湯",
    "author": "Mingwangx at Chinese Wikipedia",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:%E8%B2%A2%E4%B8%B8%E7%B1%B3%E7%B2%89%E6%B9%AF.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/32/%E8%B2%A2%E4%B8%B8%E7%B1%B3%E7%B2%89%E6%B9%AF.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "pork-ball-rice-vermicelli-soup.jpg",
    "sourceAssetSha256": "c1a8919b8a4e602c96ef48b44ffe773a5a2af4b20d2c5d15110c486dfc829f5d",
    "cropPosition": "attention"
  },
  {
    "id": "sesame-oil-chicken",
    "commonsTitle": "File:麻油雞.jpg",
    "title": "麻油雞",
    "author": "Rockhsp",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:%E9%BA%BB%E6%B2%B9%E9%9B%9E.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/69/%E9%BA%BB%E6%B2%B9%E9%9B%9E.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "sesame-oil-chicken.jpg",
    "sourceAssetSha256": "f842a778a0d1c8b258e89b194010568fdb92affb67f16aefbe05dff7729d55d3",
    "cropPosition": "attention"
  },
  {
    "id": "taiwanese-tea-eggs",
    "commonsTitle": "File:TeaEggCloseup.JPG",
    "title": "TeaEggCloseup",
    "author": "Sjschen",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:TeaEggCloseup.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/7a/TeaEggCloseup.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "taiwanese-tea-eggs.jpg",
    "sourceAssetSha256": "91d649ca040c6eb4513ffc04ad9e02c72c32b4fd307980feba885b233c1843e3",
    "cropPosition": "attention"
  },
  {
    "id": "taiwanese-sausage",
    "commonsTitle": "File:Pine and Crane DTLA - taiwanese sausage.jpg",
    "title": "Pine and Crane DTLA - taiwanese sausage",
    "author": "Benoît Prieur",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pine_and_Crane_DTLA_-_taiwanese_sausage.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Pine_and_Crane_DTLA_-_taiwanese_sausage.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "taiwanese-sausage.jpg",
    "sourceAssetSha256": "77eaeefe3e8b714fac1ab823a08109e15ddd37d268f0aca6cdc26c8140c36727",
    "cropPosition": "attention"
  },
  {
    "id": "small-sausage-big-sausage",
    "commonsTitle": "File:Dachang Bao Xiaochang (大腸包小腸 Small Sausage in Big Sausage) (8446244651).jpg",
    "title": "Dachang Bao Xiaochang (大腸包小腸 Small Sausage in Big Sausage) (8446244651)",
    "author": "istolethetv",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Dachang_Bao_Xiaochang_(%E5%A4%A7%E8%85%B8%E5%8C%85%E5%B0%8F%E8%85%B8_Small_Sausage_in_Big_Sausage)_(8446244651).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Dachang_Bao_Xiaochang_%28%E5%A4%A7%E8%85%B8%E5%8C%85%E5%B0%8F%E8%85%B8_Small_Sausage_in_Big_Sausage%29_%288446244651%29.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "small-sausage-big-sausage.jpg",
    "sourceAssetSha256": "947a76fcf2961636e693351b3c70950a12c098866c11e2721862f0f83c27d586",
    "cropPosition": "east",
    "cropZoom": 1.5
  },
  {
    "id": "milkfish-congee",
    "commonsTitle": "File:臺南飲食 虱目魚鹹粥.jpg",
    "title": "臺南飲食 虱目魚鹹粥",
    "author": "Sin-siōng",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:%E8%87%BA%E5%8D%97%E9%A3%B2%E9%A3%9F_%E8%99%B1%E7%9B%AE%E9%AD%9A%E9%B9%B9%E7%B2%A5.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/8/84/%E8%87%BA%E5%8D%97%E9%A3%B2%E9%A3%9F_%E8%99%B1%E7%9B%AE%E9%AD%9A%E9%B9%B9%E7%B2%A5.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "milkfish-congee.jpg",
    "sourceAssetSha256": "c5a4bebea4b605e48e6cfe3483dc19e9cd8111eb51bf6a4f018f0f98d3ceba96",
    "cropPosition": "attention"
  },
  {
    "id": "pineapple-cakes",
    "commonsTitle": "File:Pineapple Pastry.JPG",
    "title": "Pineapple Pastry",
    "author": "Mk2010",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pineapple_Pastry.JPG",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/64/Pineapple_Pastry.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "pineapple-cakes.jpg",
    "sourceAssetSha256": "400f013b0651c327a9b8a816d6551d1adc13dedf5903bd703c5bea0b7c88c0a3",
    "cropPosition": "attention"
  },
  {
    "id": "jiufen-taro-balls",
    "commonsTitle": "File:Taro Balls at Jiufen, New Taipei City, Sept 2011.jpg",
    "title": "Taro Balls at Jiufen, New Taipei City, Sept 2011",
    "author": "Raychang27",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Taro_Balls_at_Jiufen,_New_Taipei_City,_Sept_2011.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Taro_Balls_at_Jiufen%2C_New_Taipei_City%2C_Sept_2011.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "jiufen-taro-balls.jpg",
    "sourceAssetSha256": "f8c609b063b5be27448606b215671617ada40d271b41d0fe015721e196547f3c",
    "cropPosition": "attention"
  },
  {
    "id": "coffin-bread",
    "commonsTitle": "File:Coffin bread - Tainan, Taiwan (2017).jpg",
    "title": "Coffin bread - Tainan, Taiwan (2017)",
    "author": "Riblet15",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Coffin_bread_-_Tainan,_Taiwan_(2017).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/e1/Coffin_bread_-_Tainan%2C_Taiwan_%282017%29.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "coffin-bread.jpg",
    "sourceAssetSha256": "249edad8841943bb61fbc1696026ef911f731b2092fdd9ed23254515c546d5e3",
    "cropPosition": "attention"
  },
  {
    "id": "taiwanese-oil-rice",
    "commonsTitle": "File:Mushroom & Glutinous Oil Rice.jpg",
    "title": "Mushroom & Glutinous Oil Rice",
    "author": "Ralff Nestor Nacor",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Mushroom_%26_Glutinous_Oil_Rice.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Mushroom_%26_Glutinous_Oil_Rice.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "taiwanese-oil-rice.jpg",
    "sourceAssetSha256": "b022cb09e78bea014938b4547b118b6df8121a02982fc331cd66ccc5adf04c11",
    "cropPosition": "attention"
  },
  {
    "id": "peanut-shaved-ice",
    "commonsTitle": "File:Close-up shot of Taiwanese shaved ice with peanuts at Yang-Ji on 30 August 2017.jpg",
    "title": "Close-up shot of Taiwanese shaved ice with peanuts at Yang-Ji on 30 August 2017",
    "author": "迷惘的人生",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Close-up_shot_of_Taiwanese_shaved_ice_with_peanuts_at_Yang-Ji_on_30_August_2017.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/69/Close-up_shot_of_Taiwanese_shaved_ice_with_peanuts_at_Yang-Ji_on_30_August_2017.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true,
    "sourceAsset": "peanut-shaved-ice.jpg",
    "sourceAssetSha256": "c5b67cb371361dd4bac07d699206a9745d4815e66a5992c74a275cfa4b5fae27",
    "cropPosition": "attention"
  }
];

export default taiwanesePhotoCandidates;
