// Generated from pinned, visually reviewed Wikimedia Commons photographs.
// Run node scripts/generate-vietnamese-photo-manifest.mjs to verify and regenerate.
export const vietnamesePhotoCandidates = [
  {
    "id": "pho-bo",
    "commonsTitle": "File:Beef noodle soup (Phở bò) - Pho Hanoi Authentic 2024-12-01.jpg",
    "title": "Beef noodle soup (Phở bò) - Pho Hanoi Authentic 2024-12-01",
    "author": "Andy Li",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Beef_noodle_soup_(Ph%E1%BB%9F_b%C3%B2)_-_Pho_Hanoi_Authentic_2024-12-01.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/65/Beef_noodle_soup_%28Ph%E1%BB%9F_b%C3%B2%29_-_Pho_Hanoi_Authentic_2024-12-01.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "pho-bo.jpg",
    "sourceAssetSha256": "20a40e7fc2990136d6c1e496669a8758785b5132ed2af6961e6fcc5149020619",
    "cropPosition": "east",
    "cropZoom": 1.2,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Clear beef broth, flat noodles, thin beef, onion and green herbs; tight right crop excludes the neighboring diner.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "pho-ga",
    "commonsTitle": "File:Pho ga (noodle soup with chicken), Hanoi (6945821707).jpg",
    "title": "Pho ga (noodle soup with chicken), Hanoi (6945821707)",
    "author": "David McKelvey from Brisbane, Australia",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Pho_ga_(noodle_soup_with_chicken),_Hanoi_(6945821707).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/1/10/Pho_ga_%28noodle_soup_with_chicken%29%2C_Hanoi_%286945821707%29.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "pho-ga.jpg",
    "sourceAssetSha256": "330895f467a333d67ecc7b4996e4cc4ab732553fb8c7bdd827d8aab3a2e15cd2",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Pale poached chicken, flat noodles, clear broth, scallions, onion and sliced chile; no hoisin garnish in the chosen source.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bun-bo-hue",
    "commonsTitle": "File:Bun-Bo-Hue-from-Huong-Giang-2011.jpg",
    "title": "Bun-Bo-Hue-from-Huong-Giang-2011",
    "author": "Kham Tran - www.khamtran.com",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bun-Bo-Hue-from-Huong-Giang-2011.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/0/00/Bun-Bo-Hue-from-Huong-Giang-2011.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceAsset": "bun-bo-hue.jpg",
    "sourceAssetSha256": "29f3c98bd396eae3e96061d1ada11445d52bcf5845a24492774c6f3ea9a217d3",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Red lemongrass broth with sliced beef, pork, herbs and chile; no visible blood cake or sausage.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bun-rieu",
    "commonsTitle": "File:Bowl of Vietnamese bun rieu soup with tomato.jpg",
    "title": "Bowl of Vietnamese bun rieu soup with tomato",
    "author": "HungryHuy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bowl_of_Vietnamese_bun_rieu_soup_with_tomato.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/30/Bowl_of_Vietnamese_bun_rieu_soup_with_tomato.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "bun-rieu.jpg",
    "sourceAssetSha256": "96cf297e5150a8d4f31c5f898be392ba472fcc521204043c518e193f162a77d3",
    "cropPosition": "south",
    "cropZoom": 1.12,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Tomato broth, crab-pork-egg curds, fried tofu, noodles, tomato and scallions; rejected blood/sausage source is not published.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bun-cha",
    "commonsTitle": "File:Bun-cha-hanoi.jpg",
    "title": "Bun-cha-hanoi",
    "author": "Valentin Orange",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bun-cha-hanoi.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Bun-cha-hanoi.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "bun-cha.jpg",
    "sourceAssetSha256": "b24016e9218df9e29c1e4bfe23e8bbeed2382008f22ac69a75834c31794cad54",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Grilled pork in amber dip, separate rice vermicelli and herbs, disclosed optional fried rolls.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bun-thit-nuong",
    "commonsTitle": "File:Vietnamese grilled pork with rice noodles and fish sauce.jpg",
    "title": "Vietnamese grilled pork with rice noodles and fish sauce",
    "author": "HungryHuy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Vietnamese_grilled_pork_with_rice_noodles_and_fish_sauce.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Vietnamese_grilled_pork_with_rice_noodles_and_fish_sauce.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "bun-thit-nuong.jpg",
    "sourceAssetSha256": "d46f3eddd97dac170f4560afffef5232fc468aacbf35ecb40f069fd1987c5789",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Grilled sliced pork, rice noodles, pickled carrot/daikon, cucumber, peanuts, herbs and disclosed optional fried rolls.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "goi-cuon",
    "commonsTitle": "File:Gỏi cuốn.jpg",
    "title": "Gỏi cuốn",
    "author": "Tran Hai Duong",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:G%E1%BB%8Fi_cu%E1%BB%91n.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/9/90/G%E1%BB%8Fi_cu%E1%BB%91n.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "goi-cuon.jpg",
    "sourceAssetSha256": "b4b0febadbe90de458083d2606e11811ef801ab5ccaef255ddfb0e95e9473e71",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Transparent rice-paper rolls containing shrimp, pork, vermicelli and herbs; a few cooked shrimp halves are arranged alongside.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "cha-gio",
    "commonsTitle": "File:Chả giò (Vietnamese Spring Rolls) - 12.jpg",
    "title": "Chả giò (Vietnamese Spring Rolls) - 12",
    "author": "Satdeep Gill",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ch%E1%BA%A3_gi%C3%B2_(Vietnamese_Spring_Rolls)_-_12.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Ch%E1%BA%A3_gi%C3%B2_%28Vietnamese_Spring_Rolls%29_-_12.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "cha-gio.jpg",
    "sourceAssetSha256": "b3ba07c20926bba79547ec9c7f2a0daa8dc8705cc8200b59160a99d07405e081",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Blistered pale-golden fried rice-paper rolls with amber garlic-herb dipping sauce; no decorative vegetable flowers.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "banh-xeo",
    "commonsTitle": "File:Bánh xèo 1.jpg",
    "title": "Bánh xèo 1",
    "author": "Kent Wang from Austin, TX",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:B%C3%A1nh_x%C3%A8o_1.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/e/e5/B%C3%A1nh_x%C3%A8o_1.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "banh-xeo.jpg",
    "sourceAssetSha256": "d3febd5a25c4eef74a4d4857e4196f54c9d238e91554b548bee930fd53d3ee38",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Thin yellow opened crepe, shrimp and pork filling, onion, sprouts and leafy serving herbs.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "banh-cuon",
    "commonsTitle": "File:Banh Cuon, Chez Y Lan, Paris 2 November 2016 001.jpg",
    "title": "Banh Cuon, Chez Y Lan, Paris 2 November 2016 001",
    "author": "Guilhem Vellut from Paris, France",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Banh_Cuon,_Chez_Y_Lan,_Paris_2_November_2016_001.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/d/df/Banh_Cuon%2C_Chez_Y_Lan%2C_Paris_2_November_2016_001.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "banh-cuon.jpg",
    "sourceAssetSha256": "ef0c62c13af6bc4d9f0fc356169fea78b10368c4463b85364a3dd28a221ce6a7",
    "cropPosition": "attention",
    "cropZoom": 1.25,
    "reviewedAt": "2026-09-12",
    "reviewNote": "White translucent steamed-style rice rolls with dark wood-ear/pork filling, fried shallots and green herbs.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "banh-mi-thit",
    "commonsTitle": "File:Bánh mì thịt nguội.jpg",
    "title": "Bánh mì thịt nguội",
    "author": "Minh Nguyen",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:B%C3%A1nh_m%C3%AC_th%E1%BB%8Bt_ngu%E1%BB%99i.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/6/6c/B%C3%A1nh_m%C3%AC_th%E1%BB%8Bt_ngu%E1%BB%99i.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "banh-mi-thit.jpg",
    "sourceAssetSha256": "e990b9fdbe70c8f31f87699f877b268e28f48ee2f781be88edf00bb96ead55b1",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Baguette with pink pork ham, pale sausage, pate, cucumber, cilantro and pickle strands.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "com-tam-suon-nuong",
    "commonsTitle": "File:Cơm tấm SG (cơm sườn) ng27th9n2020 (2).jpg",
    "title": "Cơm tấm SG (cơm sườn) ng27th9n2020 (2)",
    "author": "Phương Huy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:C%C6%A1m_t%E1%BA%A5m_SG_(c%C6%A1m_s%C6%B0%E1%BB%9Dn)_ng27th9n2020_(2).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/5/5e/C%C6%A1m_t%E1%BA%A5m_SG_%28c%C6%A1m_s%C6%B0%E1%BB%9Dn%29_ng27th9n2020_%282%29.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "com-tam-suon-nuong.jpg",
    "sourceAssetSha256": "34daac70237987518ff04353abfdece4764a5c6f19e4a742ecb0ca54fab5e665",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Caramelized thin pork chop, white broken rice, scallion oil and cucumber; no egg loaf or pork skin.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "cao-lau",
    "commonsTitle": "File:Cao Lau - close-up - Ba Be, Hoi An Market VND15000.jpg",
    "title": "Cao Lau - close-up - Ba Be, Hoi An Market VND15000",
    "author": "avlxyz",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Cao_Lau_-_close-up_-_Ba_Be,_Hoi_An_Market_VND15000.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Cao_Lau_-_close-up_-_Ba_Be%2C_Hoi_An_Market_VND15000.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceAsset": "cao-lau.jpg",
    "sourceAssetSha256": "f1244b93f40fcacf426531e8be5ee867300c16b3a295ebdd0766aaa8f5182f1d",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Thick ivory-brown noodles, browned sliced pork, herbs and crisp golden square toppings with little broth.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "mi-quang",
    "commonsTitle": "File:Mi Quang at Ngoc Mai (with noodles uncovered).jpg",
    "title": "Mi Quang at Ngoc Mai (with noodles uncovered)",
    "author": "Gary Stevens",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Mi_Quang_at_Ngoc_Mai_(with_noodles_uncovered).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/2/27/Mi_Quang_at_Ngoc_Mai_%28with_noodles_uncovered%29.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "mi-quang.jpg",
    "sourceAssetSha256": "bbd2e26e9e93f1c9487e3b3f9c0f27910bd946dee16bc4b0849e989c2c1c1a6c",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Yellow wide rice noodles, cooked tail-on shrimp and sliced pork, sesame rice crackers, crushed peanuts, greens and shallow broth. Rejected white-noodle/tomato/dried-shrimp candidate is not published.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "ca-kho-to",
    "commonsTitle": "File:Phú Quốc 2022 (cá kho tộ) (2).jpg",
    "title": "Phú Quốc 2022 (cá kho tộ) (2)",
    "author": "Phương Huy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ph%C3%BA_Qu%E1%BB%91c_2022_(c%C3%A1_kho_t%E1%BB%99)_(2).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/d/db/Ph%C3%BA_Qu%E1%BB%91c_2022_%28c%C3%A1_kho_t%E1%BB%99%29_%282%29.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "ca-kho-to.jpg",
    "sourceAssetSha256": "31024236d536edb4080d3da8dc3bc01da16bb71706dfcd5d782e487a1e9ca828",
    "cropPosition": "south",
    "cropZoom": 1.25,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Skin-on fish steaks in glossy caramel reduction with scallions and pepper in a stovetop-safe metal pot.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "thit-kho-trung",
    "commonsTitle": "File:Vietnamese thit kho, braised pork belly and boiled eggs.jpg",
    "title": "Vietnamese thit kho, braised pork belly and boiled eggs",
    "author": "HungryHuy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Vietnamese_thit_kho,_braised_pork_belly_and_boiled_eggs.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Vietnamese_thit_kho%2C_braised_pork_belly_and_boiled_eggs.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "thit-kho-trung.jpg",
    "sourceAssetSha256": "89834677fcc4fa5c6dea125ce567ca1ccfe69576591e52357d3838c1c9de0ee1",
    "cropPosition": "south",
    "cropZoom": 1.2,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Large skin-on pork belly and whole boiled eggs in amber coconut-water braise. Normal crop excludes the original bottom watermark and side pickles.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bo-kho",
    "commonsTitle": "File:Bo Kho (cropped).jpg",
    "title": "Bo Kho (cropped)",
    "author": "Jason Hutchens",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bo_Kho_(cropped).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/48/Bo_Kho_%28cropped%29.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "bo-kho.jpg",
    "sourceAssetSha256": "1efb85b9c67761dd675344de3c9edb918321db377aaea2ffd9eea8940210f584",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Large tender beef pieces, carrots, glossy red-brown broth and fresh Thai basil. Rejected tripe/radish/noodle version is not published.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "canh-chua-ca",
    "commonsTitle": "File:Canh chua cá lóc ở Thủy Trúc Quán, đường Nguyễn Nhữ Lãm (3).jpg",
    "title": "Canh chua cá lóc ở Thủy Trúc Quán, đường Nguyễn Nhữ Lãm (3)",
    "author": "Phương Huy ( thảo luận )",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Canh_chua_c%C3%A1_l%C3%B3c_%E1%BB%9F_Th%E1%BB%A7y_Tr%C3%BAc_Qu%C3%A1n,_%C4%91%C6%B0%E1%BB%9Dng_Nguy%E1%BB%85n_Nh%E1%BB%AF_L%C3%A3m_(3).jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/4/43/Canh_chua_c%C3%A1_l%C3%B3c_%E1%BB%9F_Th%E1%BB%A7y_Tr%C3%BAc_Qu%C3%A1n%2C_%C4%91%C6%B0%E1%BB%9Dng_Nguy%E1%BB%85n_Nh%E1%BB%AF_L%C3%A3m_%283%29.jpg",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Template:PD-self",
    "sourceAsset": "canh-chua-ca.jpg",
    "sourceAssetSha256": "d5a6aee68bb351bfdaae5672c3374f4c37c1bdb8952c9396218e330c50d35809",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Clear sour fish soup with pineapple, tomato, okra, sprouts, edible bac ha stems and chopped herbs.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "bun-bo-nam-bo",
    "commonsTitle": "File:Bun Bo Nam Bo 20230106 111344.jpg",
    "title": "Bun Bo Nam Bo 20230106 111344",
    "author": "01x07x2022000",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Bun_Bo_Nam_Bo_20230106_111344.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Bun_Bo_Nam_Bo_20230106_111344.jpg",
    "license": "CC0 1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceAsset": "bun-bo-nam-bo.jpg",
    "sourceAssetSha256": "b2b9acfe4b3269566e213375877585bd8339c9283f1876eaa620e452c834866b",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Thin stir-fried beef over white vermicelli, blanched sprouts, pickled carrot, crushed peanuts and fried shallots; greens underneath.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "che-ba-mau",
    "commonsTitle": "File:Chendol2.jpg",
    "title": "Chendol2",
    "author": "Jess Lander from Los Angeles, CA, USA",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Chendol2.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/7/75/Chendol2.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceAsset": "che-ba-mau.jpg",
    "sourceAssetSha256": "c6dc8be84fe23c9b977bef9e5f4f97f8fd68abcb6b2f0c1ba13d484a5f1a7105",
    "cropPosition": "centre",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Whole-bean variation: red beans, pale black-eyed peas, green jelly strands and coconut layer in clear cups.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  },
  {
    "id": "banh-flan",
    "commonsTitle": "File:Ly bánh lăng (flan) Việt Nam.jpg",
    "title": "Ly bánh lăng (flan) Việt Nam",
    "author": "Phương Huy",
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Ly_b%C3%A1nh_l%C4%83ng_(flan)_Vi%E1%BB%87t_Nam.jpg",
    "originalFile": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Ly_b%C3%A1nh_l%C4%83ng_%28flan%29_Vi%E1%BB%87t_Nam.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceAsset": "banh-flan.jpg",
    "sourceAssetSha256": "28f19b907f117190f27b32d12e47b77ac366591409ed84f4c069b18b0e94c91f",
    "cropPosition": "attention",
    "cropZoom": 1,
    "reviewedAt": "2026-09-12",
    "reviewNote": "Yellow caramel custard in a cup with coffee sauce and crushed ice, explicitly included as a serving option.",
    "relation": "dish-reference",
    "commercialUseVerified": true,
    "realPhoto": true,
    "visualMatchApproved": true
  }
];

export default vietnamesePhotoCandidates;
